### ISSUE TITLE
Improve error handling documentation to cover how errors end pulling

### ISSUE THREAD

**Issue by jrduncans** [typelevel/fs2#1245]
None of the current examples show more items available upstream after the element that causes an error, so it's not clear the `handleErrorWith` or `attempt` won't cause those elements to be pulled.

**Comment by mpilquist** [comment]
This is a common question -- should probably be added to the FAQ as well as covered in a new guide section on stream error handling strategies.

**Comment by geoffjohn11** [comment]
I'd like to try to create pr to add this documentation.

**Comment by SystemFw** [comment]
that's great!
There's some discussion here if you need inspiration https://gitter.im/functional-streams-for-scala/fs2?at=5ebbd511faa128031ccbe9e8 but you don't have to use it :)
