### ISSUE TITLE
Allow creation of an empty Topic

### ISSUE THREAD

**Issue by Porcupine96** [typelevel/fs2#1330]
Hello!

First of all, thank you for creating and maintaining such a great library. 

I was wondering if there's any reason that creation of a `Topic` always requires passing the `initial` element? I guess the user could always keep the value wrapped in an `Option` but wouldn't the API be a bit more pleasant if we provide a second `apply` which does not take any parameters? If I'm missing something, please let me know :) 

I provided a basic implementation in: #1329. 

Cheers,

**Comment by mpilquist** [comment]
This is fixed as of 31b5f20bd
