### ISSUE TITLE
FS3: Stack safety of Pull

### ISSUE THREAD

**Issue by mpilquist** [typelevel/fs2#1437]
On the `topic/fs3` branch, we've removed `FreeC` and replaced it with putting all functionality in to `Pull`. Each pull constructor must implement two abstract methods, `step` and `translate`. This differs quite a bit from 1.0, where `FreeC` provided stack safety, sequencing, error handling, and interruption and the stream algebra provided everything else. Instead, the FS3 `Pull` has to provide all of that functionality, leaning on the effect type's capabilities when possible.

One downside of this approach is that many `Pull` constructors, if implemented naively, end up not stack safe. The effect type is stack safe (as guaranteed due to `Sync[F]` constraint), but that's not sufficient. In particular, any pull constructor which implements `step` or `translate` by first calling the same method on another `Pull` is not stack safe. Contrast this with pulls that compute some effectful value and then binds on the result before calling the same method on another `Pull` -- in such a case, stack safety is ensured by `F`.

We currently have a couple adhoc attempts at fixing this (e.g. in `Pull#flatMap`, `Pull#flatMapOutput`, `Pull#handleErrorWith`) but these solutions aren't the right approach. For example, `Pull#mapOutput` is still broken, as well as interleavings like `flatMap(f1).handleErrorWith(h1).flatMap(f2).handleErrorWith(h2).flatMap(f3).handleErrorWith(h3)`.

We might be able to solve this by changing `step` to track it's own depth along with inserting a trampoline every so often.

**Comment by SystemFw** [comment]
> We currently have a couple adhoc attempts at fixing this (e.g. in Pull#flatMap, Pull#flatMapOutput, Pull#handleErrorWith)
>as well as interleavings like flatMap(f1).handleErrorWith(h1).flatMap(f2).handleErrorWith(h2).flatMap(f3).handleErrorWith(h3)

So, interleavings of stack safe methods end up not being stack safe?

**Comment by mpilquist** [comment]
> So, interleavings of stack safe methods end up not being stack safe?

Right, sort of (or at least I believe so, I haven't tried it) -- and that's b/c the way in which I implemented stack safety for `flatMap` was condensing call stacks like `flatMap(f).flatMap(g).flatMap(h)` in to a single `flatMap`. That's the wrong approach though -- `flatMap` isn't really stack safe with the current approach, it just pretends to be.

**Comment by diesalbla** [comment]
@mpilquist Just sweeping through old issues. What are your plans regarding the `fs3` now?

The `develop` branch (soon to become version 3.0) is now using separate `Pull` constructors for `Step` and `Translate`. Some of the interpretation is moved to handlers, and at some places there we have found and patched some stack-unsafety.

**Comment by mpilquist** [comment]
I think fs3 is overcome by events at this point.
