### ISSUE TITLE
Write scalafix upgrade for 1.0 to 1.1/2.0

### ISSUE THREAD

**Issue by mpilquist** [typelevel/fs2#1511]
The 1.1.0-M1 (soon to be relabeled as 2.0) release is mostly source compatible with 1.0.x, with a handful of exceptions:
- replaced use of blocking execution contexts with `cats.effect.Blocker`
- changed TCP/UDP support to use `SocketGroup`
- maybe changed `Pull#stream` and `Pull#streamNoScope` to require result type to be `Unit`

A scalafix upgrade script that automates as much of those as possible would be fantastic.

**Comment by fthomas** [comment]
It would be twice as fantastic if the Scalafix migration would then be added to [Scala Steward](https://github.com/fthomas/scala-steward/blob/master/docs/scalafix-migrations.md) before the final release. :-)
