### ISSUE TITLE
Add more operations to fs2-io to make it a fully featured file library

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/fs2#1533]
We talked about this on gitter at some point and the lack of a fully featured file library in the cats-effect ecosystem is something that should be addressed.

Below are some features I'd like to see added to `fs2-io`, note that a lot of those aren't streaming operations, but I feel like they're still very much relevant here.

- moving files 
- deleting files
- copying files
- create directories
- list files and folders at given path
- check if file or folder exists
- read filesystem metadata
- symlinks
- permissions
- temp files

I can start working on some of these soon if no one objects :)

**Comment by ybasket** [comment]
I like the idea and would be in for contributing some code - did you start working on it already?

**Comment by LukaJCB** [comment]
Yes, I can push a WIP branch :)

**Comment by ybasket** [comment]
Just opened a PR for listing files, complementing your WIP, but there are still operations missing in case someone wants to contribute :)

**Comment by r-glyde** [comment]
Hi. Is there still an interest in adding more of the functionality above and is anyone else working on them? I think some towards the bottom of the list are not done yet. I was going to look at permissions unless anyone else plans to.

**Comment by r-glyde** [comment]
Hi @LukaJCB, just wondering what sort of implementation you had in mind for the temporary files (and I guess directories as well)? I was initially assuming a stream from a resource that would delete the file during the release? Or were you thinking more just create a wrapper for `nio.Files.createTempFile` and leave deletion for the user at some other point?

**Comment by diesalbla** [comment]
Going through the list of items on the opening message, it looks as if the `Files[F[_]]` trait, together with `FileHandle[F[_]]`, are implementing most of the features requested on this Issue. This, together with the lack of activity for a year, is good  reason to close this issue.
