### ISSUE TITLE
Microsite title doesn't fit into jumbotron on mobile

### ISSUE THREAD

**Issue by kubukoz** [typelevel/fs2#1762]
![Screenshot_20200124-234228](https://user-images.githubusercontent.com/894884/73109390-4303dd80-3f03-11ea-9c11-3e12d45b8b49.jpg)

Should we customize the text size, or make it more concise?

**Comment by kubukoz** [comment]
I think we could drop "effectful". Concurrency implies effects.

**Comment by mpilquist** [comment]
I'd drop "Purely" and "for Scala" too. "Functional Concurrent Streams"?

**Comment by mpilquist** [comment]
Or maybe just "Functional Streams" and leave the details to the rest of the site :)

**Comment by SystemFw** [comment]
I'd leave `concurrent` there if it fits, `functional` is not a high-information word for those not already familiar with pure FP

**Comment by SystemFw** [comment]
Eh, maybe not actually :)

**Comment by kubukoz** [comment]
I actually agreed with that though!

**Comment by kubukoz** [comment]
Fits now, closing.

![Screenshot_20201128-063443.jpg](https://user-images.githubusercontent.com/894884/100494656-e507de00-3143-11eb-9d5a-fcd2f0f86ce7.jpg)
