### ISSUE TITLE
Add temp(Directory|File)(Resource|Stream) overloads without the dir parameter

### ISSUE THREAD

**Issue by nigredo-tori** [typelevel/fs2#1851]
`Files.createTempDirectory` and `Files.createTempFile` have overloads without the `dir` parameters. Those create directories and files in the standard temporary directory (`/tmp` on Linux). The using code shouldn't be forced to search for a good place for temporary data, so it makes sense for us to implement this functionality as well.

**Comment by diesalbla** [comment]
This issue seems to have been solved in https://github.com/typelevel/fs2/pull/2107, which made the `dir` parameter into an `Option`. For this reason, this can be closed. However, @nigredo-tori please reopen if the current solution is not satisfactory.
