### ISSUE TITLE
RFC: FS2 3.0 Ideas

### ISSUE THREAD

**Issue by mpilquist** [typelevel/fs2#1940]
We opened the `develop` branch today, which is for FS2 3.0 development. The default branch is still `main` and we'll merge `main` to `develop` every so often.

The primary theme of FS2 3.0 is [Cats Effect 3](https://github.com/typelevel/cats-effect/tree/ce3) support and support for Scala 3. CE3 is very close to the point where we can start integrating -- just need an `IO` type to land, which should be very soon. Given this will be a binary incompatible release, we can also do some cleanup (e.g. #1938 #1939).

CE3 will support Scala 2.12, 2.13, and 3.0, so we'll likely follow suit. Supporting 2.12 isn't a big deal and there's really not much we'd gain by dropping it.

Is there anything else we want to tackle? Maybe #1913? :)

**Comment by diesalbla** [comment]
@mpilquist Since we are aiming at releasing 3.0 soon, is there any need to keep this open?
