### ISSUE TITLE
Add support for unix sockets

### ISSUE THREAD

**Issue by Taig** [typelevel/fs2#1999]
Following [this discussion on Gitter](https://gitter.im/functional-streams-for-scala/fs2?at=5ee91725ef5c1c28f028a60b) it appears feasible to add support for unix sockets to fs2 based on [jnr-unixsockets](https://github.com/jnr/jnr-unixsocket).

As a use case example this could benefit a library like [tpolecat/skunk](https://github.com/tpolecat/skunk) to talk to a postgres database via unix sockets as it is done on Google Cloud (Run).

**Comment by mpilquist** [comment]
I think @ChristopherDavenport implemented this recently. I'd be happy to incorporate it in to fs2-io if Chris wants but knowing Chris, it's already available somewhere. :)

**Comment by ChristopherDavenport** [comment]
https://github.com/ChristopherDavenport/whale-tail/blob/master/core/src/main/scala/io/chrisdavenport/whaletail/UnixSocket.scala - Works like a charm. Was going to move it into a library of its own.

**Comment by ChristopherDavenport** [comment]
Always happy to get code off my hands though if you want it.

**Comment by ChristopherDavenport** [comment]
Otherwise I was going to move it into something like fs2-unixsocket or something to that effect here shortly. Was finishing ember to prove all my concepts work. But its pretty solid at communicating with the docker daemon already.

**Comment by ChristopherDavenport** [comment]
Alright, going to contribute this as a new module to fs2 as long as everyone is happy.

**Comment by Taig** [comment]
I don't have an immediate use for this, I was just investigating the topic and wanted to document the gitter discussion in the issues to provide a better point of reference for other people searching for this. Knowing that I can find a solution for this in the whaletail repo is totally sufficient for me, but having a proper fs2 module would certainly be a convenient solution.

**Comment by keynmol** [comment]
Probably a very rare use-case, but the jnr-unixsocket library relies on https://github.com/jnr/jnr-ffi which makes use of dynamic class loading for platform-specific stuff, which breaks immediately when building with graalvm native-image (no fallback)

Also there's JEP effort to provide a generic solution in the JDK itself: https://openjdk.java.net/jeps/380 which hopefully won't rely on dynamic class loading, so should be more portable.

**Comment by mpilquist** [comment]
Fixed by #2376 -- supports both JEP380 and JNR

**Comment by guizmaii** [comment]
Hi everyone,

Is it enabled by default or is there an option to activate the use of this Unix socket? 🤔

**Comment by armanbilge** [comment]
@guizmaii To use unix sockets you either need JDK 16 (I think) or to add a dependency to `"com.github.jnr" % "jnr-unixsocket" % "0.38.8"`. Otherwise it will throw an error.

**Comment by vasilmkd** [comment]
What @armanbilge said. One more little detail is that they are only supported in `fs2` `3.x`.

**Comment by guizmaii** [comment]
Thanks guys! 🙂

**Comment by guizmaii** [comment]
Can we use these Unix sockets to connect to a remote DB (with Skunk in my case)? 🤔

**Comment by mbaechler** [comment]
> Can we use these Unix sockets to connect to a remote DB (with Skunk in my case)? thinking

I don't think so, unix sockets are local to a kernel AFAIK

**Comment by guizmaii** [comment]
@mbaechler What about @taig initial comment: 

> as it is done on Google Cloud (Run).

We're using Google Cloud too!

**Comment by guizmaii** [comment]
Apparently not the best idea even if possible in Google Cloud, apparently! Thanks for your help @mbaechler 🙂

**Comment by taig** [comment]
@guizmaii If you can, I'd recommend setting up a GCP VPC network, using only private IPs on your SQL instances and connect to those directly.
