### ISSUE TITLE
SignallingRef#access problems

### ISSUE THREAD

**Issue by durban** [typelevel/fs2#2018]
The current (v2.4.4) implementation of the `access` method of `SignallingRef` seems to have some problems (as far as I can tell, since v2.4.0, in #1889):

- It calls `equals` in [this line](https://github.com/typelevel/fs2/blob/v2.4.4/core/shared/src/main/scala/fs2/concurrent/Signal.scala#L200). It seems at least unintuitive, that an operation which is basically a compare-and-swap would use value equality.
- Regardless of the previous issue, `access` doesn't seem to work. That is, in a simple case (no contention), it cannot change the value in the ref. (Maybe the `==` should be `!=` instead? It might work that way, although the first issue would remain.)

**Comment by SystemFw** [comment]
yeah that sounds weird. I'll have a look later, thanks for reporting :)

**Comment by mpilquist** [comment]
I have no recollection of changing the implementation of `access` as represented in that PR...

**Comment by SystemFw** [comment]
I think you just restored the old implementation since PubSub had a leak, and given that `access` is pretty much never used, and especially not on Signal, it's likely it has always been broken...

**Comment by mpilquist** [comment]
Ah, thanks, that makes sense.

**Comment by SystemFw** [comment]
Haven't forgotten about this :)

There is some bigger cleanup I want to do on Signal in `develop`, after which we can backport an `access` fix to `main`

**Comment by mpilquist** [comment]
@SystemFw Any more thoughts on this one?

**Comment by SystemFw** [comment]
oh, I think I fixed it in #2041 , but the automatic closing didn't trigger
