### ISSUE TITLE
readOutputStream binds the OutputStream to the writing thread's lifetime

### ISSUE THREAD

**Issue by nigredo-tori** [typelevel/fs2#2037]
Consider this stream (FS2 2.4.4):
```scala
readOutputStream(blocker, 1024) { os =>
  blocker.delay[IO, Unit] {
    val t = new Thread(
      () => os.write(123)
    )
    t.start
    t.join
    Thread.sleep(1000)
  }
}
```
When run (OpenJDK 11), it produces this exception:
```
java.io.IOException: Write end dead
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:310)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at fs2.io.package$.$anonfun$readBytesFromInputStream$1(io.scala:77)
...
```
This is caused by an absolutely ridiculous `PipedInputStream` gotcha - it throws an error if the last `Thread` to write to the `PipedOutputStream` has completed without closing the stream! This is a 20 year old [wontfix](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-4028322). :facepalm: 

Tying the `OutputStream` to a particular thread is extremely confusing, even more so in the Cats/FS2 context. We should fix this - or at the very least add a warning to the documentation and to the scaladoc.

**Comment by vasilmkd** [comment]
I'd like to work on this.
