### ISSUE TITLE
Race condition in reactivestreams StreamSubscriber

### ISSUE THREAD

**Issue by vigoo** [typelevel/fs2#2076]
There is a race condition in `StreamSubscriber` between `onNext` and `onComplete` because they run the effects manipulating the underlying state machine via `f.runAsync().unsafeRunSync` (in the `Runner` implicit class). 

This can lead to a case where `OnNext` arrives in the `UpstreamCompletion` state. 

(I found this issue with AWS SDK's [SimpleHttpContentPublisher](https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/SimpleHttpContentPublisher.java) connected to a http4s request entity stream)

**Comment by SystemFw** [comment]
If you have the time, a repro test case would be awesome.

Completely coincidentally, someone posted your project https://github.com/vigoo/prox in the cats-effect dev channel a couple of days ago, I think it would make a great addition to the fs2 ecosystem page https://fs2.io/ecosystem.html, if you wish to include a link to it there

**Comment by vigoo** [comment]
Thanks, that would be nice. I'll open a PR for adding it, and will also try to add a test (and maybe a fix) for this issue.

**Comment by vigoo** [comment]
@SystemFw the above pull request has a test case reproducing the issue, and also a fix.

**Comment by SystemFw** [comment]
Thanks, I'll have a look soon, once I get some time :)

**Comment by vigoo** [comment]
@SystemFw @mpilquist  do you think it would be possible to release this fix as a 2.4.5?
