### ISSUE TITLE
Wrong type for FS2[Nothing, INT]

### ISSUE THREAD

**Issue by SarpongAbasimi** [typelevel/fs2#2141]
I have just started using fs2 and according to the documentation the type for 
`Stream(1,2)` should be `[Nothing, Int]` but I am getting an error for this.

```  
  def traverse(data: Stream[Nothing, Int]) = {
    Traverse[List].traverse[Option, Int, Int](data.toList)((eachElementInData) => Option(eachElementInData))
  }
```

when I pass in `Stream(1,2,3)` as data, I get an error saying
```Error:(13, 24) type mismatch;
 found   : fs2.Stream[[x]fs2.Pure[x],Int]
 required: fs2.Stream[Nothing,Int]
        traverse(Stream(1,2))```

Can anybody help or explain why this is the case thank you.

**Comment by SarpongAbasimi** [comment]
@mpilquist or anyone could explain why this is the case?

**Comment by ChristopherDavenport** [comment]
```
def traverse(data: Stream[fs2.Pure, Int]) = {
    Traverse[List].traverse[Option, Int, Int](data.toList)((eachElementInData) => Option(eachElementInData))
  }
```

A stream of only elements is a `Stream[Pure, *]`

**Comment by mpilquist** [comment]
Yeah, like @ChristopherDavenport said, streams which evaluate no effects are of type `Stream[Pure, A]` for some `A`. Any `Stream[Nothing, A]` can be automatically converted to a `Stream[Pure, A]` but the inverse isn't true.

Where in the docs did you see a claim that `Stream(1, 2)` should return a `Stream[Nothing, Int]`? That's likely a holdover from back before we had the `Pure` type constructor.

**Comment by SarpongAbasimi** [comment]
@mpilquist  in the is says `val s1a = Stream(1,2,3)` is `// s1a: Stream[Nothing, Int]` and even emit `s1 = Stream.emit(1)` is of type `s1: Stream[Nothing, Int]`


<img width="988" alt="Screen Shot 2020-11-18 at 13 54 34" src="https://user-images.githubusercontent.com/37377831/99539065-af296380-29a5-11eb-92bb-399f3910a9f7.png">

**Comment by SarpongAbasimi** [comment]
@mpilquist and @ChristopherDavenport  used the example in the documentation -> https://fs2.io/guide.html
under `Building streams`

<img width="668" alt="Screen Shot 2020-11-18 at 14 01 33" src="https://user-images.githubusercontent.com/37377831/99540061-f106d980-29a6-11eb-9aa0-f64bd31859d2.png">

**Comment by mpilquist** [comment]
Ah, that's a limitation of type inference in Scala 2. The types you see in the doc snippet are a result of the Scala REPL evaluation. I don't think there's any way to correct that.

**Comment by SarpongAbasimi** [comment]
Okay that explains it. Than you very much
