### ISSUE TITLE
Simplify and improve documentation on Queue

### ISSUE THREAD

**Issue by LLCampos** [typelevel/fs2#2213]
I'm trying to learn to use `Queue` and struggling even to have a simple hello-wordish example working (add stuff to the queue, take it out and print it).

I find the examples in [here](https://fs2.io/concurrency-primitives.html) and [here](https://fs2.io/guide.html) to be way too complex for a introduction on `Queue`. It would be nice to have some really simple example, accompanied with a detailed example of what's happening.

**Comment by LLCampos** [comment]
Here's my proposal (inspired by this [SO answer](https://stackoverflow.com/a/65762139/5082718)):

```scala
import cats.effect.{ConcurrentEffect, ContextShift, IO, Timer}
import fs2.Stream
import fs2.concurrent.{NoneTerminatedQueue, Queue}

import scala.concurrent.ExecutionContextExecutor

implicit val ec: ExecutionContextExecutor = scala.concurrent.ExecutionContext.global
implicit val cs: ContextShift[IO] = IO.contextShift(ec)
implicit val c: ConcurrentEffect[IO] = IO.ioConcurrentEffect
implicit val t: Timer[IO] = IO.timer(ec)

def enqueueValues(queue: NoneTerminatedQueue[IO, Int]) = {
  // Have to wrap stream's values in Option because of the type of queue we're using
  val stream = Stream(1,2,3).map(Some(_))
  // Enqueues each value in stream
  val enqueuingStream = stream.through(queue.enqueue)
  // Terminate stream
  enqueuingStream ++ Stream.eval(queue.enqueue1(None))
}

val program = for {
  queue <- Queue.noneTerminated[IO, Int] // Queue that terminates when None is enqueued
  _ <- enqueueValues(queue).compile.drain
  result <- queue.dequeue.compile.toList
} yield result

program.unsafeRunSync()
```

**Comment by mpilquist** [comment]
Note that `Queue` has moved to cats-effect (in the `cats.effect.std` package) in the forthcoming CE3 / FS2 3 releases.

**Comment by LLCampos** [comment]
I think we can close this one down. then. ;)
