### ISSUE TITLE
Make .showLinesStdOut and friends use Console instead of Sync?

### ISSUE THREAD

**Issue by kubukoz** [typelevel/fs2#2338]
CE3 introduces a `Console[F]` algebra - should we use that instead of Sync in `showLines` and `showLinesStdOut`? What about `.debug`?

**Comment by mpilquist** [comment]
Yes for `showLines` and `showLinesStdOut`, though note we'll have to change signatures b/c `showLines` currently takes a `PrintStream`. I'm fine if we get rid of the `PrintStream` variant entirely. We also should use the default parameter trick to get a show instance for any O.

`debug` should stay as-is -- ceremony in making that effectful will cause it not to be used as much.

**Comment by mpilquist** [comment]
We should make a pass through the stream combinators and evaluate each use of `Sync`. I just looked at a couple and it appears we can replace `Sync` with stuff like `Clock`, `Random`, etc. Need to do this before 3.0 final.
