### ISSUE TITLE
Cannot find Scaladoc on fs2.io website

### ISSUE THREAD

**Issue by ScalaWilliam** [typelevel/fs2#2356]
Hi fs2 team!

I am unable to find fs2's ScalaDoc through the fs2.io website.

![image](https://user-images.githubusercontent.com/2464813/113355589-ec7d0500-9338-11eb-8c47-3d45a47e7f19.png)

**Comment by mpilquist** [comment]
I think we have Scaladoc links in the README but not the site. Let's update those to use javadoc.io and then make sure they get put on the site somewhere obvious.
