### ISSUE TITLE
Stream interrupt closing resource to stop blocking socket operation has stopped working in version 3?

### ISSUE THREAD

**Issue by m50d** [typelevel/fs2#2362]
Hi,

In fs2 2.5.4 the following program "works" (that is, it exits after 1 second with a no such element error from `lastOrError`):

````
import java.net.ServerSocket

import cats.effect.{IO, IOApp, Resource}
import fs2.Stream

import scala.concurrent.duration._

object Example extends IOApp.Simple {
  override def run: IO[Unit] =
    Stream.resource(Resource.make(IO.delay(new ServerSocket(1234)))(s => IO.delay(s.close())))
      .evalMap(s => IO.delay[Unit](s.accept()))
      .interruptAfter(1 second)
      .compile.lastOrError
}
````

In fs2 3.0.1 the same program instead hangs indefinitely. I experimented with using `IO.interruptible` but couldn't achieve anything - from what I read elsewhere interrupting a thread during blocking socket operations doesn't generally work and it's necessary to close the socket instead.

Is this an intended behaviour change? If so, what's the right way to express this kind of pattern in fs2 3?

**Comment by m50d** [comment]
(I'm testing on Windows 10, FWIW)

**Comment by mpilquist** [comment]
This definitely should still work. Here's a further minimization:

```scala
scala> Stream.bracket(IO.println("acq"))(_ => IO.println("fin")).evalMap(_ => IO.sleep(1.minute)).interruptAfter(1.second).compile.drain.unsafeRunSync()
acq
fin

scala> Stream.bracket(IO.println("acq"))(_ => IO.println("fin")).evalMap(_ => IO(Thread.sleep(100000L))).interruptAfter(1.second).compile.drain.unsafeRunSync()
acq
// hangs
```

**Comment by mpilquist** [comment]
Simpler reproduction:

```scala
scala> Stream.eval(IO(Thread.sleep(10000L))).interruptAfter(1.second).compile.drain.unsafeRunSync()
// Runs for 10 seconds
scala> Stream.eval(IO.sleep(10.seconds)).interruptAfter(1.second).compile.drain.unsafeRunSync()
// Runs for 1 second
```

**Comment by mpilquist** [comment]
Thanks to a reminder from @oleg-py and @kubukoz, this behavior is indeed intentional. Racing two fibers back pressures on cancelation of the losing fiber. The `IO.delay` constructor results in an uncancelable fiber. In general, using `IO.interruptible` is the right fix, but as you noted, `ServerSocket#accept` is not interruptible.

One option is to restore the leaky behavior of CE2 via:

```scala
.evalMap(s => IO.delay[Unit](s.accept()).start.flatMap(_.joinWithNever))
```

Another option is using the socket support in fs2-io or fs2-netty, which both build on non-blocking IO.

**Comment by m50d** [comment]
Thanks. The fiber start works as a workaround. In my actual use case the uninterruptible blocking socket call is deep in a library where I can't easily replace it.
