### ISSUE TITLE
Reconsider type of `eval_`

### ISSUE THREAD

**Issue by HuwCampbell** [typelevel/fs2#2366]
I've just been fighting against a bug based on me using `eval_` instead of `eval`. By convention, functions ending in `_` return `Unit`, not `Void`. For example, whenever I see
```scala
for {
  ...
  _ <- traverse f as
  ...
} yield ???
```
I will replace `traverse` with `traverse_`.

I had something like this:
```scala
for {
  status <- streamJob
  _      <- Stream.eval_(updateTracker)
} yield status
```

I assumed this would yield values still. I know that I could have used `evalTap` or `eval` here, but I feel like the API really bit me.

**Comment by nikiforo** [comment]
Yes, this behavior is unintuitive. Moreover, everything below `eval_` wouldn't be evaluated, because, as you've said, `eval_` produces `Void`
```
for {
  status <- streamJob
  _      <- Stream.eval_(updateTracker)
  _      <- Stream.eval(Sync[F].delay(println("I won't evaluate")))
} yield status
```
Thus, `eval_` should be used when concatenating streams with `++`, but not with flatMap operations.

Concerning your issue, `eval_` is already deprecated.
```
  @deprecated("Use exec if passing an F[Unit] or eval(fa).drain if passing an F[A]", "2.5.0")
  def eval_[F[_], A](fa: F[A]): Stream[F, INothing] =
    new Stream(Pull.eval(fa).map(_ => ()))
```

**Comment by HuwCampbell** [comment]
Thanks. If there's nothing actionaly I will close.
