### ISSUE TITLE
`parEvalMap` + `Sync` => interrupt called for Scope that cannot be interrupted

### ISSUE THREAD

**Issue by Taig** [typelevel/fs2#2371]
```scala
import cats.effect.{Concurrent, IO, IOApp, Sync}
import fs2.Stream

object Main extends IOApp.Simple {
  def source[F[_]](implicit F: Concurrent[F]): Stream[F, Int] =
    Stream.emits(1 to 100).covary[F].parEvalMap(maxConcurrent = 2)(x => F.pure(x))

  def runF[F[_]: Sync](source: Stream[F, Int]): F[Int] = source.compile.lastOrError

  override def run: IO[Unit] = runF[IO](source[IO]).void
}
```

```
java.lang.IllegalStateException: Scope#interrupt called for Scope that cannot be interrupted
	at fs2.internal.Scope.interruptWhen(Scope.scala:400)
	at fs2.Pull$.$anonfun$compile$12(Pull.scala:1013)
	at fs2.internal.Scope.$anonfun$acquireResource$2(Scope.scala:189)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:493)
	at cats.effect.IOFiber.execR(IOFiber.scala:1077)
	at cats.effect.IOFiber.run(IOFiber.scala:137)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:372)
```

This is an error I encountered while upgrading to fs2 3. Note that when replacing the `Sync` constraint with `Concurrent` (and thereby probably also the inferred compiler instance), the code works as expected. Also `parEvalMapUnordered` does not trigger the error.

Edit: I tried to come up with a naive replacement in the meantime that just enqueues a bunch of `Deferred`s but was surprised to see the exact same stacktrace while using the usual `fs2.Stream` combinators such as `concurrently` or `merge`, so the issue is probably more fundamental than `parEvalMap`.

**Comment by mpilquist** [comment]
Yeah, this happens any time a stream containing `interruptWhen` is compiled with the "synchronous compiler" provided here: https://github.com/typelevel/fs2/blob/bb69f51505d7871af318da56be5281f25fa6b5af/core/shared/src/main/scala/fs2/Compiler.scala#L169-L173

With a full `Concurrent[F]`, you get the fully featured compiler here: https://github.com/typelevel/fs2/blob/bb69f51505d7871af318da56be5281f25fa6b5af/core/shared/src/main/scala/fs2/Compiler.scala#L180-L188

Conceptually, `interruptWhen` could capture a `Concurrent[F]` constraint, but then translation/`mapK` gets much more difficult (from 2.5.x: https://github.com/typelevel/fs2/blob/5d2580ac99cfb39517dca35c66ab6c47d60aff02/core/shared/src/main/scala/fs2/internal/Algebra.scala#L673-L731)

**Comment by Taig** [comment]
Thank you for the detailed explanation

**Comment by kubukoz** [comment]
What do you think about having this in the error message?

**Comment by rossabaker** [comment]
This one is a menace with Doobie.  Sharing in case it saves anyone else some time.

I couldn't find `interruptWhen` in our code or in Doobie's.  I started tearing up fs2, and came up with these functions that can embed an `InterruptWhen` in the stream.  More or less the ones that require `Concurrent`, which isn't surprising in hindsight:

```
    221:  broadcastThrough
    542:  concurrently
    636:  debounce
    874:  either
   1061:  evalFilterAsync
   1081:  evalFilterNotAsync
   1498:  hold
   1506:  holdOption
   1511:  holdResource
   1524:  holdOptionResource
   1584:  interruptAfter
   1604:  interruptWhen
   1633:  interruptWhen
   1639:  interruptWhen
   1646:  interruptWhen
   1744:  mapAsync
   1753:  mapAsyncUnordered
   1800:  switchMap
   1859:  merge
   1920:  mergeHaltBoth
   1929:  mergeHaltL
   1938:  mergeHaltR
   2065:  parEvalMapUnordered
   2164:  parZip
   2172:  parZipWith
   2178:  pauseWhen
   2205:  prefetch
   2211:  prefetchN
   2642:  timeout
   3785:  observe
   3789:  observeAsync
   3839:  observeEither
   3937:  parJoin
   4063:  parJoinUnbounded
   4465:  timed
```

`WeakAsync.liftK` to get an `IO ~> ConnectionIO` gets us demoted to the `Sync` compiler, which doobie uses internally in a couple places.  We called its `PHLOS` with a stream sourced from `mapAsync` and ate flaming death.
