### ISSUE TITLE
Add partial apply factory for SignallingRef

### ISSUE THREAD

**Issue by arosien** [typelevel/fs2#2396]
`apply` and `of` require both `F[_]` and `A` parameters, which often has inference issues requiring the user to annotate. Instead these methods could use the partial apply "trick" to infer at least the `A` type.

```scala
def apply[F[_], A](initial: A)(implicit arg0: Concurrent[F]): F[SignallingRef[F, A]]
```

Other data types might have similar issues, but this is the one I've noticed so far.

**Comment by kubukoz** [comment]
I think this would be nice to have.

For anyone who wants to give this a try: see what `Ref[F].of` looks like in cats-effect, but instead of using `Ref.Make[F]` use `Concurrent[F]`.

**Comment by IVaSmi** [comment]
Hi
I would like to make this issue. Ok?

**Comment by kubukoz** [comment]
Sounds good to me! Feel free to ask if you need any help.
