### ISSUE TITLE
.evalTap seems to be off by one after .sliding

### ISSUE THREAD

**Issue by DarkWingMcQuack** [typelevel/fs2#2428]
I am trying to do something like this:
```scala 
fs2.Stream
    .emits(1 to 50)
    .covary[IO]
    .evalTap(dp => IO.println(f"before sliding: $dp"))
    .sliding(5)
    .evalTap(ch => IO.println(f"after sliding: ${ch}"))
```
the printed result turns out to start with:
```
before sliding: 5
after sliding: Chunk(1, 2, 3, 4, 5)
before sliding: 6
before sliding: 7
after sliding: Chunk(2, 3, 4, 5, 6)
```
it almost seems like one chunk output is skipped.
after this the output follows this pattern:
```
before sliding: x
after sliding: Chunk(x-5, x-4, x-3, x-2, x-1)
```
and at the end the output then catches up again to be something like:
```
before sliding: 50
after sliding: Chunk(45, 46, 47, 48, 49)
after sliding: Chunk(46, 47, 48, 49, 50)
```

shouldn't the output always be something like:
```
before sliding: x
after sliding: Chunk(x-4, x-3, x-2, x-1, x)
```
???
For cats-effect-2.4.1 and fs2-2.5.4 this works as expected,
but for cats-effect-3.1.0 and fs2-3.0.4 the strange off by one output is generated.

I created a small repository which demonstrates this strange behaviour:
[Example](https://github.com/DarkWingMcQuack/fs2-bug-example)

For a further explanation, i am using an infinite stream and i am logging diagnostics via `evalTap`, and it seems that after the `.sliding` the most recent datapoint is always missing in the chunks i recieve.

**Comment by mpilquist** [comment]
@nikiforo Maybe related to #2221

**Comment by kubukoz** [comment]
fun unrelated thing, if you use `.debug()` instead of `evalTap` you first see all elements from `before`, then all the elements from `after`.

**Comment by nikiforo** [comment]
Yep, I'm looking at it.
My first guess is that it's an intended behavior.
The thing is that between `.evalTap(dp => IO.println(f"before sliding: $dp"))` and `.evalTap(ch => IO.println(f"after sliding: ${ch}"))` is that there is a buffer, that should be filled to be emit the chunk.
However, I'm looking at the issue.

**Comment by mpilquist** [comment]
@kubukoz Insert a `.unchunk` after `Stream.emits` to avoid any confusing results due to a single large chunk getting emitted.

**Comment by mpilquist** [comment]
Smaller reproduction using debugChunks:

```scala
@ Stream.emits(1 to 10).unchunk.debugChunks(x => "before: " + x).sliding(5).debugChunks(c => "after: " + c).toList
before: Chunk(1)
before: Chunk(2)
before: Chunk(3)
before: Chunk(4)
before: Chunk(5)
after: Chunk(Chunk(1, 2, 3, 4, 5))
before: Chunk(6)
before: Chunk(7)
after: Chunk(Chunk(2, 3, 4, 5, 6))
before: Chunk(8)
after: Chunk(Chunk(3, 4, 5, 6, 7))
before: Chunk(9)
after: Chunk(Chunk(4, 5, 6, 7, 8))
before: Chunk(10)
after: Chunk(Chunk(5, 6, 7, 8, 9))
after: Chunk(Chunk(6, 7, 8, 9, 10))
```

**Comment by mpilquist** [comment]
Issue is here: https://github.com/typelevel/fs2/blob/1450b7f7a85bb81ca33e408e30ad685e8f3a7ddd/core/shared/src/main/scala/fs2/Stream.scala#L2399-L2400

The first time through this function, we have `window = Chunk(2, 3, 4, 5)` and `prev = empty`. We then uncons a `Chunk(6)` which gives us `heads = Chunk(6)` and `tails = empty`. The while loop condition fails so we recurse, passing `window = Chunk(2, 3, 4, 5)` and `heads = Chunk(6)`. We could have emitted that `2, 3, 4, 5, 6` though.

**Comment by mpilquist** [comment]
Yep, I'll close now
