### ISSUE TITLE
Streaming Data With FS2

### ISSUE THREAD

**Issue by SarpongAbasimi** [typelevel/fs2#2435]
Hey 👋🏿

I am trying to stream data from the twitter api `https://api.twitter.com/2/tweets/sample/stream`
Ref - `https://developer.twitter.com/en/docs/twitter-api/tweets/sampled-stream/api-reference/get-tweets-sample-stream`

For the client I have this 

<img width="888" alt="Screen Shot 2021-06-05 at 18 54 22" src="https://user-images.githubusercontent.com/37377831/120900910-7b571800-c62f-11eb-8d1b-cfcee2eedf83.png">

with sample tweet being 

```
final case class Id(id: Int)                   extends AnyVal  
final case class Text(text: String)            extends AnyVal
final case class Data(id: Id, text: Text)
final case class SampleTweet(data: Data) extends Tweet
```

but when I make a request, I get this error `expected eof got '{"data...' (line 2, column 1)`

There isn't a comma `,` after each `data`. (I think that is the reason for the error)

<img width="1166" alt="Screen Shot 2021-06-05 at 18 46 34" src="https://user-images.githubusercontent.com/37377831/120901025-341d5700-c630-11eb-9ab8-33b0c685af63.png">

This makes me think that I am probably not handling the stream well. Please is there a better way to handle streams in `fs2`?

**Comment by nikiforo** [comment]
I think you'll find more help on gitter or discord(both links can be found on the main github page) for this kind of questions.
