### ISSUE TITLE
Stream.fromQueue* could take a QueueSource instead of a Queue

### ISSUE THREAD

**Issue by arosien** [typelevel/fs2#2437]
I believe the signatures for `Stream.fromQueueUnterminated`, etc., could be narrowed to take `QueueSource` instead of `Queue`, because they only rely on the `take` and `tryTake` methods. Then if users want to translate a `Queue` to a `Stream` they don't have to require knowledge of the "write" methods of the `Queue`, only the "read" methods.

**Comment by kubukoz** [comment]
Agreed. I don't know if this will be a binary compatible change, though - if not, we can probably work around by making the existing functions package-private and adding new ones.

**Comment by djspiewak** [comment]
Should be binary compatible since it's a contravariant parameter adjustment.

**Comment by armanbilge** [comment]
> Should be binary compatible since it's a contravariant parameter adjustment

I thought this too! But, MiMa didn't agree, I'd be really really interested to hear an explanation for why.

**Comment by mpilquist** [comment]
@djspiewak These are static methods, not class methods.

**Comment by armanbilge** [comment]
`fromQueue` is static, but the `enqueue` methods I also modified in my PR are class methods.
