### ISSUE TITLE
Stream returned from Queue#dequeue is halted on subsequent call to take

### ISSUE THREAD

**Issue by tgrospic** [typelevel/fs2#2440]
Use of the stream returned by `Queue#dequeue` halts unexpectedly on the second call to take element even though element should exist in the queue.

This behavior is different when using `Queue#dequeue1` which works as expected and can produce stream with all elements from the queue.

Am I missing something? Thanks!

```scala
def take2(f: Queue[IO, Int] => Stream[IO, Int]) =
  Queue.unbounded[IO, Int].flatMap { q =>
    q.enqueue1(1) *> q.enqueue1(2) *> {
      val s = f(q)
      for {
        fst <- s.take(1).compile.lastOrError
        snd <- s.take(1).compile.lastOrError
      } yield (fst, snd)
    }
  }
  .unsafeRunSync()

// Using dequeue1 produces result
take2(q => Stream.eval(q.dequeue1).repeat)

println(s"dequeue1 succeeds")

// Using dequeue halts on second call to take
take2(_.dequeue)

println(s"dequeue halted")
```
https://scalafiddle.io/sf/5Hj3iUP

fs2 version: 2.2.1 (2.5.0)

**Comment by mpilquist** [comment]
This happens b/c `dequeue` takes as many elements as are available and emits them as a single chunk in the resulting stream. Hence, the first call to `s.dequeue.take(1)` gets both values but only processes one of those values. The unprocessed entry isn't put back in to the queue. You can control this behavior via `s.dequeueChunk(maxSize)`.
