### ISSUE TITLE
Link-time errors for fs2.io on Scala.js

### ISSUE THREAD

**Issue by armanbilge** [typelevel/fs2#2479]
Building against 328a125. Maybe it's a publishing issue? Seems to specifically affect the Scalably Typed Node.js facade. @oyvindberg maybe you can help with this?

```
[info] Fast optimizing /workspace/http4s/ember-server/js/target/scala-2.12/http4s-ember-server-test-fastopt
[error] Referring to non-existent class fs2.internal.jsdeps.node.tlsMod.package$
[error]   called from fs2.io.net.tls.SecureContext$.default()fs2.io.net.tls.SecureContext
[error]   called from private fs2.io.net.tls.TLSContextCompanionPlatform$BuilderCompanionPlatform$AsyncBuilder.$anonfun$system$1()fs2.io.net.tls.TLSContext
[error]   called from fs2.io.net.tls.TLSContextCompanionPlatform$BuilderCompanionPlatform$AsyncBuilder.system()java.lang.Object
[error]   called from private org.http4s.ember.client.EmberClientBuilder.$anonfun$build$3()java.lang.Object
```

**Comment by armanbilge** [comment]
I downloaded the jar at https://repo1.maven.org/maven2/co/fs2/fs2-io_sjs1_2.12/3.0-22-328a125/ and it's missing the generated classes.

**Comment by oyvindberg** [comment]
I'll have a look today or tomorrow 👍

**Comment by oyvindberg** [comment]
Had a first look. None of the generated files or class files compiled from them are present in the jars or source jars from maven central, but they must have been there while building.

if I `publishLocal` the files end up where they should:
```
$ jar -tf io/js/target/scala-2.12/fs2-io_sjs1_2.12-3.0-22-328a125.jar|grep tlsMod.package
fs2/internal/jsdeps/node/tlsMod/package.class
fs2/internal/jsdeps/node/tlsMod/package$.class
fs2/internal/jsdeps/node/tlsMod/package.sjsir
fs2/internal/jsdeps/node/tlsMod/package$.sjsir
```

Might there be a whole in the logic for compressing target folders in the CI github actions maybe?

**Comment by mpilquist** [comment]
It may be due to sbt-osgi, which limits the JAR to include fs2.io packages. I would have thought that only impacted the JVM build though. Simplest fix is likely using `fs2.io` as the root package for generated code -- e.g., `fs2.io.jsdeps`

**Comment by armanbilge** [comment]
Thank you both for the fast response! Much appreciated. I think OSGI is the likely candidate, going to try disabling it for Scala.js
