### ISSUE TITLE
Fs2-IO Java Resources API

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/fs2#2503]
Right now there are Files and Network, but another commonly used component is java resources. 

Might be cool to have that integrated so that folks can just reference resources via strings or as streams, etc. I asked in discord and it seemed like there may be interest. So before taking a stab at it I figured it'd make sense to open an issue to track it.

Similar to how StaticFile in http4s does so perhaps? https://github.com/http4s/http4s/blob/7ef1ef1930e5a4dcfb8b73043c3368e1acd8c34a/core/src/main/scala/org/http4s/StaticFile.scala#L34

Thoughts appreciated.

**Comment by Daenyth** [comment]
I have some basic stuff around this, but only rudimentary
https://gist.github.com/Daenyth/67575575b5c1acc1d6ea100aae05b3a9#file-testresource-scala-L10

**Comment by rossabaker** [comment]
Impure.  `URLClassLoader` references the file system and has mutable state, and a custom `ClassLoader` can do even more unholy things.

**Comment by armanbilge** [comment]
Here you go: https://github.com/typelevel/fs2/pull/2733
