### ISSUE TITLE
can't find TransformingStreams.scala

### ISSUE THREAD

**Issue by martijnhoekstra** [typelevel/fs2#252]
The example CreatingStreams.scala refers to a TransformingStreams.scala which I can't find. Is it missing? I'm also missing examples on Tee and Wye, but I'm not sure if that's a separate issue, or this issue.

**Comment by peterneyens** [comment]
There still is one reference in `CreatingStreams.scala` to `TransformingStreams.scala` on [line 112](https://github.com/scalaz/scalaz-stream/blob/master/src/test/scala/scalaz/stream/examples/CreatingStreams.scala#L112).
