### ISSUE TITLE
performance degradation when using chunkN

### ISSUE THREAD

**Issue by komarov134** [typelevel/fs2#2603]
We faced performance degradation when we started to use fs2 3.x in our app.
[async-profiler](https://github.com/jvm-profiling-tools/async-profiler) helped us to locate the problem:
```
--- 4219943188 ns (53.96%), 421 samples
  [ 0] scala.collection.immutable.List.reverse
  [ 1] scala.collection.immutable.Queue.tail
  [ 2] fs2.Chunk$Queue.go$1
  [ 3] fs2.Chunk$Queue.apply
  [ 4] fs2.Chunk.map
```

Code sample:
---
fs2 3.1.1 / cats-effect 3.1.1 / Scala 2.13.6
---
```scala
  val s1 = Stream.range(0, 10000).flatMap(x => Stream.emits(List.fill(10)(x)))
  val s2 = s1.chunkN(100000)

  s2.map(chunk => chunk.map(_ + 1)).compile.drain          // took 19500 ms
  s2.map(chunk => chunk.compact.map(_ + 1)).compile.drain  // took 250 ms
```

s1 is a stream of chunks all having size 10. While s2 is a stream of the single chunk, but this chunk is constructed (see `Chunk.Queue`) of many little chunks. And if you don't use `.compact` before doing `.map` you get O(L^2) time complexity where L is the number of small chunks used to construct a big chunk.

Despite the fs2.Chunk docs provide a caution about using Chunk in this way, it is constructed implicitly (inside `.chunkN`) in the provided example. And an indexed lookup (which is O(L)) is used inside `.map`.

fs2 2.x used `toChunk` in `unconsN` in order to make Chunk.Queue accessible by index for O(1). Why is it not used now?

**Comment by diesalbla** [comment]
@komarov134 The relevant code, for the `chunkN` method of `Stream, is [here](https://github.com/typelevel/fs2/blob/main/core/shared/src/main/scala/fs2/Stream.scala#L4053-L4077).

**Comment by diesalbla** [comment]
@komarov134 Would you like to take care of submitting a PR with the fix, at least for this `unconsN` method? You can reproduce that sample over the local branch. There may be other places where such chunk concatenations also would benefit from compacting.

**Comment by mpilquist** [comment]
Nice find!

It can be tricky to strike the right balance here. If we compact too often, performance can severely suffer, especially when the number of elements in the queue is relatively small such that the lookup is fast.

In general, I don't know if it's better for `chunkN` to compact or not. If so, what other methods should get a similar treatment?

**Comment by mpilquist** [comment]
Some more thoughts about this issue here: https://github.com/typelevel/fs2/issues/2627#issuecomment-924862270
