### ISSUE TITLE
Memory leak when using mergeHaltL

### ISSUE THREAD

**Issue by adamw** [typelevel/fs2#2604]
Fs2 version: 3.1.1
cats-effect version: 3.2.8

When running the below with `-Xmx50m`, I get an OOM after about 30 seconds:

```scala
import cats.effect.{IO, IOApp}
import fs2.Stream

import scala.concurrent.duration.DurationInt

object Test extends IOApp.Simple {
  def run: IO[Unit] = Stream
    .iterate(1)(_ + 1)
    .covary[IO]
    .evalTap(_ => IO.sleep(1.millis))
    .mergeHaltL(Stream.empty) // (1)
    .evalTap(x => if (x % 1000 == 0) IO(println(x)) else IO.unit)
    .compile
    .drain
}
```

However, if I comment out `.mergeHaltL(Stream.empty) // (1)`, things nicely loop forever.

Is there something that I'm missing about `mergeHaltL`, using it incorrectly (although here I know the usage is trivial, but in reality it's a bit more complex :) ), or is there something else that is wrong?

**Comment by mpilquist** [comment]
@adamw Thanks! I suspect this was just fixed today. Could you try running the same example with 3.1-52-5c8346c and reporting back?

**Comment by adamw** [comment]
Yes, works great, thank you! :) That's a new standard on fixing bugs, even before I reported the issue ;)

**Comment by mpilquist** [comment]
Ha! Thanks for testing. I'm going to get an official 3.1.2 out later tonight.
