### ISSUE TITLE
compactUntagged class cast exception

### ISSUE THREAD

**Issue by 0minus273** [typelevel/fs2#2679]
Bonjour!

Reproduction:

```scala
Chunk.Queue.singleton(Chunk.singleton(1)).traverse(x => Option(x))
```

Result: java.lang.ClassCastException: class fs2.Chunk$Singleton cannot be cast to class fs2.Chunk$ArraySlice

First was discovered when using evalMapChunk. 

Introduced [here](https://github.com/typelevel/fs2/pull/2630/files) in v3.1.3 with compactUntagged implementation.

**Comment by Alexey-Yuferov** [comment]
@mpilquist it looks good for me
