### ISSUE TITLE
parjoin hangs when streams are terminated early

### ISSUE THREAD

**Issue by Swoorup** [typelevel/fs2#2703]
fs2 version: 3.2.1

Even when the inner stream has already terminated it appears that, parJoin doesn't appear the complete the stream. This however depends on the time the inner stream are being terminated once the merged stream is created?

Scastie Link:  https://scastie.scala-lang.org/PwbiIsCOTSOwU0xDhLNVTw
Comment Line 91 to observe the issue. Oddly it doesn't happen when there is a delay in the first element.

**Comment by mpilquist** [comment]
Without the sleep on line 91, the message sent on line 92 is published prior to the subscription to the topic starting up. This is a race condition where the broker stream on lines 84-90 is starting concurrently with line 92.

**Comment by Swoorup** [comment]
@mpilquist yeah, that seems to explain it, I wonder if there is a way to ensure subscription starts before publishing.

**Comment by Swoorup** [comment]
nvm, I could wait for the number of subscribers to wait before continuing to run publishers using
Topics: `def subscribers: fs2.Stream[cats.effect.IO, Int]`
