### ISSUE TITLE
par* hangs when receives IO.cancel as an effect to evaluate

### ISSUE THREAD

**Issue by nikiforo** [typelevel/fs2#2712]
consider this:
```
  test("evalMap") {
    val stream = Stream(IO.canceled).covary[IO].evalMap(identity)
    stream.onFinalizeCase(c => IO.println(c)).compile.drain
  }

  test("parEvalMap cancelled") {
    val stream = Stream(IO.canceled).covary[IO].parEvalMap(2)(identity)
    stream.onFinalizeCase(c => IO.println(c)).compile.drain
  }

  test("parEvalMapUnordered cancelled") {
    val stream = Stream(IO.canceled).covary[IO].parEvalMapUnordered(2)(identity)
    stream.onFinalizeCase(c => IO.println(c)).compile.drain
  }

  test("parJoin cancelled") {
    val stream = Stream(Stream.eval(IO.canceled)).repeatN(2).covary[IO].parJoinUnbounded
    stream.onFinalizeCase(c => IO.println(c)).compile.drain
  }
```

Only the first one(evalMap) cancels the stream. Other three hangs the stream.

**Comment by djspiewak** [comment]
My guess is that someone is using `embedNever`. A better approach in this case would be `embed(F.canceled *> F.never)`

**Comment by nikiforo** [comment]
Similar approach was suggested by @SystemFw on [discord](https://discord.com/channels/632277896739946517/632278585700384799/910295890386886716). However, I asked it quite differently...
For `parEvalMap` the solution might be to change `Deferred[F, Either[Throwable, O2]` to `Deferred[F, Outcome]`, fill it with `.guaranteeCase(o => deferred.complete(o).void)`, read from it with`.get.flatMap(_.embed(IO.cancel >> IO.never)`.

**Comment by nikiforo** [comment]
`parEvalMap` correct implementation requires https://github.com/typelevel/fs2/issues/2714

**Comment by nikiforo** [comment]
There is no practical value in defining the behavior of `Stream(IO.canceled).evalMap(identity).compile.drain`
