### ISSUE TITLE
StreamDecoder isn't well defined to work with bytes, bits and other repeatable codecs

### ISSUE THREAD

**Issue by nikiforo** [typelevel/fs2#2747]
There are several examples, yet they show a single issue.

1. Consider this code:
```scala
test("Stream decode 3") {
val c1 = constant(hex"0000")
val c2 = bytes

val s = Stream.emits(hex"0000".bits.toByteArray).covary[IO]

val d1 = StreamDecoder.isolate(16)(StreamDecoder.once(c1 ~> c2))
val d2 = StreamDecoder.isolate(16)(StreamDecoder.once(c1) *> StreamDecoder.once(c2))
def run(d: StreamDecoder[ByteVector]) = s.through(d.toPipeByte).compile.toList

(run(d1), run(d2))
  .mapN { case(r1, r2) =>
    val msg =
      s"""combine codecs: $r1
         |combine stream: $r2""".stripMargin
    IO.println(msg)
  }
  .flatten
  .unsafeRunSync()
}
```

Expected result:
```
combine codecs: List(ByteVector(empty))
combine stream: List(ByteVector(empty))
```

Actual result:
```
combine codecs: List(ByteVector(empty))
combine stream: List()
```

2. Also, consider this case:

```scala
val s1 = Stream.chunk(Chunk.byteVector(hex"1234")).covary[IO]
val s2 = Stream.chunk(Chunk.byteVector(hex"5678")).covary[IO]
val s = s1 ++ s2

test("bits1") {
  val actual = s.through(StreamDecoder.once(bytes).toPipeByte).compile.toList.unsafeRunSync()
  println(actual)
}

test("bits2") {
  val actual = s.through(StreamDecoder.isolate(32)(StreamDecoder.once(bytes)).toPipeByte).compile.toList.unsafeRunSync()
  println(actual)
}
```

Expected result:
```
List(ByteVector(4 bytes, 0x12345678))
List(ByteVector(4 bytes, 0x12345678))
```

Actual result:
```
List(ByteVector(2 bytes, 0x1234))
List(ByteVector(4 bytes, 0x12345678))
```

3. And this one:
```scala
test("repeat") {
  val s1 = Stream.chunk(Chunk.byteVector(hex"12341234"))
  val s2 = Stream.chunk(Chunk.byteVector(hex"1234"))

  val pipe = StreamDecoder.once(vector(constant(hex"1234"))).toPipeByte[IO]
  val actual = (s1 ++ s2).covary[IO].through(pipe).compile.toList.unsafeRunSync()
  println(actual)
}
```

Expected result: `List(Vector((), (), ()))`
Actual result: `List(Vector((), ()))`

I don't know whether any of them should be considered a bug. I understand the implications of changing the behavior to comply to expectations from examples 2, 3. However, [comments](https://github.com/typelevel/fs2/blob/18e0eb9e718aba6620db22efc9fa61a4a552990d/scodec/shared/src/main/scala/fs2/interop/scodec/StreamDecoder.scala#L37) state that expectations from examples 2, 3 should be fullfilled.

**Comment by mpilquist** [comment]
2 & 3 make sense to me -- both cases are a result of `StreamDecoder.once` being satisfied after the wrapped decoder decodes successfully. When combined with codecs that consume a variable number of bytes, the chunk structure ends up changing the decode result. Not sure about 1 though.

**Comment by nikiforo** [comment]
Yes, there are actually two distinct cases - the first example and the other two. Now all of them make sense to me. Thanks!

**Comment by Dessix** [comment]
I just ran into this limitation in my own project. Would it be viable to compensate for this by retrying parsing on success such that variable-length- and tail-distance-based codecs are able to pull in more content up until the result produces a remainder or a failure? Not being able to base things off of the "end" of the stream is restrictive for some formats, and this chunk-related leak of the abstraction seems to be the most addressable cause.
