### ISSUE TITLE
Unexpected behaviors around the use of Pull (part II)

### ISSUE THREAD

**Issue by LLCampos** [typelevel/fs2#2762]
```scala
  "org.typelevel" %% "cats-effect" % "3.2.9",
  "co.fs2" %% "fs2-core" % "3.2.3",
```

Similar to https://github.com/typelevel/fs2/issues/2717.

```scala
  def run: IO[Unit] = {
    val stream = Stream.emit(1).map(Left(_)) ++ Stream(Right("a"))
    val streamModified: Stream[IO, (String, Int)] = stream.pull.uncons1
      .flatMap { case Some((Left(_), s)) =>
        s.collect { case Right(b) => b }.through(pipeFailure).pull.echo
      }
      .void
      .stream
    streamModified
      .evalTap(_ => IO.unit)
      .debug()
      .compile
      .drain
  }

  private def pipeFailure: Stream[IO, String] => Stream[IO, (String, Int)] =
    _.zipWith(Stream.emit(0).repeat)((_, _))

  private def pipeSuccess: Stream[IO, String] => Stream[IO, (String, Int)] =
    _.map(v => (v, 0))
```

I would expect `pipeFailure` and `pipeSuccess` to be equivalent, but they don't seem to be in this scenario?

1a) If I use `pipeFailure`, nothing is logged.
1b) If I use `pipeSuccess`, `(a,0)` is logged

I also would expect `Stream.emit(1).map(Left(_))` to be equivalent to `Stream.emit(Left(1))` but, using `pipeFailure`:

2a) if I have `Stream.emit(1).map(Left(_))`, nothing is logged.
2b) If I have `Stream.emit(Left(1))`, `(a,0)` is logged.

**Comment by mpilquist** [comment]
Confirmed same as @nikiforo - appears to work fine with v3.2.3:

```
➜  cat foo.scala | highlight --syntax scala --out-format truecolor --style freya
// using scala 3.1.0
// using lib co.fs2::fs2-core:3.2.3
import cats.effect.{IO, IOApp}
import fs2.Stream

object DebugFs2Issue extends IOApp.Simple {

  val run: IO[Unit] = {
    val stream: Stream[IO, Either[Int, String]] =
      Stream.emit(1).map(Left(_)) ++ Stream(Right("a"))

    val streamModified: Stream[IO, (String, Int)] =
      stream.pull.uncons1.flatMap { case Some((Left(_), s)) =>
        s.collect { case Right(b) => b }.through(pipeFailure).pull.echo
      }.stream

    streamModified
      .debug()
      .compile
      .drain
  }

  private def pipeFailure: Stream[IO, String] => Stream[IO, (String, Int)] =
    _.zipWith(Stream.emit(0).repeat)((_, _))

  private def pipeSuccess: Stream[IO, String] => Stream[IO, (String, Int)] =
    _.map(v => (v, 0))
}
➜  scala-cli foo.scala
Compiling project (Scala 3.1.0, JVM)
[warn] ./foo.scala:13:37: match may not be exhaustive.
[warn]
[warn] It would fail on pattern case: None, Some((Right(_), _))
[warn]       stream.pull.uncons1.flatMap { case Some((Left(_), s)) =>
[warn]                                     ^
Compiled project (Scala 3.1.0, JVM)
(a,0)
```

**Comment by LLCampos** [comment]
Argh, yeah, I now tried to run it in the terminal and things work as expected there. The issue was that, for some reason, IntelliJ runner insisted in using the buggy version - I had to manually delete the buggy .jar from `/.cache/coursier/` to force it to use what was actually defined in `build.sbt`. :imp:

**Comment by LLCampos** [comment]
@mpilquist @nikiforo I still see unexpected behavior in `3.2.3`. Updated the example above.

**Comment by mpilquist** [comment]
Replacing the final `evalMap` with `flatMap(a => Stream.eval(IO(a)))` results in same early exit behavior. Replacing the `evalMap` with `flatMap(a => Stream(a))` works fine though. Seems like `Stream.eval` call is being evaluated in an interrupted scope (likely the one from the `zipWith`). Probably need to figure out how that interrupted scope is getting restored.

@LLCampos I'm curious about your use case -- is this coming up in a real program? Maybe there's a way to restructure to avoid this edge case?

**Comment by LLCampos** [comment]
Yup, it's coming up in a real program! :smiling_face_with_tear:

**Comment by mpilquist** [comment]
Here's a minimization:

```scala
    test("#2762 - unexpected behavior of Pull") {
      val stream = Stream(1).as(1) ++ Stream(2)
      val zippedPull =
        stream.pull.uncons1.flatMap { case Some((_, s)) =>
          s.zipWith(Stream(3))((_, _)).pull.echo
          case None => Pull.done
        }
      val actual = zippedPull.stream.evalTap(_ => IO.unit).map(identity).compile.toList
      actual.assertEquals(List((2, 3)))
    }
 ```

**Comment by mpilquist** [comment]
Fixed in https://github.com/typelevel/fs2/pull/2763

**Comment by mpilquist** [comment]
@LLCampos Can you give 3.2-51-ebb169f a try in your full program?

**Comment by LLCampos** [comment]
@mpilquist, the integration test that was failing is now passing!
