### ISSUE TITLE
onFinalize kicks in before the stream in completed.

### ISSUE THREAD

**Issue by nikiforo** [typelevel/fs2#2785]
Download branch: https://github.com/yurique/fs2/tree/feature/js-compression-platform
`sbt coreJVM/testOnly fs2.JvmCompressionSuite`
Notice that suite passes.

uncomment `onFinalize`, comment out the workaround `.flatMap` and `.handleErrorWith` here: https://github.com/typelevel/fs2/blob/a7843d07e38af28d784dee6db67e94d35ada7ea3/core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala#L350
`sbt coreJVM/testOnly fs2.JvmCompressionSuite`
Notice that suite fails.

Change `onFinalize` to `onComplete` notice that suite passes.

I think that both `onFinalize` & `onComplete` should lead to the same behavior here - test should pass(but I'm not really sure).

found by @yurique

**Comment by nikiforo** [comment]
Some minimization:
Take Compression platform that fails, run this code:
```scala
def run: IO[Unit] = {
    val bytes: List[Chunk[Byte]] =
      List(
        Chunk(31, -117, 8, 24, 0, 0, 0, 0, 4, 7, 63, 63, 63, 63, 0, 63),
        Chunk(63, 63, 63, 0, 123, 51, 119, -54, -5, -27, -13, 30, -50),
        Chunk(95, -14, 104, -59, 46, 0, 1, 47, 50, -67, 12, 0, 0, 0),
      )

    val c: Compression[IO] = Compression[IO]

    Stream
      .emits(bytes)
      .flatMap(Stream.chunk)
      .rechunkRandomly(0.1, 2)
      .debugChunks() // **
      .through(c.gunzip(8192))
      .flatMap(_.content)
      .compile
      .drain
  }
```
It fails some times, while completes during other runs. When it completes, sbt prints these warnings:
```
Non-daemon threads currently preventing JVM termination: - 171: Thread[com.swoval.files.apple.FileEventsMonitor.callback-1,5,main]
 -  - 1: Thread[main,5,main]
 -  - 14: Thread[pool-1-thread-1,5,main]
 -  - 164: Thread[FileTreeRepository-callback-executor-1,5,main]
```

If you comment out `.rechunkRandomly(0.1, 2)` and insert chunks that you've previously collected from line (**) the issue won't manifest itself.

**Comment by mpilquist** [comment]
The inflater stream is compiled and evaluated twice -- once in the implementation of `setTrailerChunk` and once in the main stream. This results in the finalizer running twice. The inflation should be refactored to avoid the need for dual compilation.

**Comment by nikiforo** [comment]
`onComplete` or `flatMap` and `handleError` changed the behavior, because they are not guaranteed to run.

In minimization `.rechunkRandomly(0.1, 2)` interferes with the problem, because `setTrailerChunk` is only called when `inflateChunk` returns a `Some`. That contributes to probabilistic results of the minimization.

**Comment by yurique** [comment]
So I tried two things:
1. eliminate the inner stream compilation: https://github.com/yurique/fs2/tree/feature/js-compression-platform-no-inner-compile ( [code](https://github.com/yurique/fs2/blob/feature/js-compression-platform-no-inner-compile/core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala#L265-L348) )
2. use `Pull.bracketCase`: https://github.com/yurique/fs2/tree/feature/js-compression-platform-pull-bracket ( [code](https://github.com/yurique/fs2/blob/feature/js-compression-platform-pull-bracket/core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala#L265-L348) )

(1) still fails the same way
(2) works

I think using `Pull.bracketCase` makes more sense here (and it works!). But I'd love to exactly pin down why `Stream.bracket` doesn't work here (or rather, what I'm mis-understanding about how it works) :) .

@mpilquist mentioned the outer stream (defined [here](https://github.com/yurique/fs2/blob/feature/js-compression-platform-pull-bracket/core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala#L241-L243)) in discord:

> likewise, this nesting: inflate: Stream[F, Byte] => Stream[F, (Stream[F, Byte], Ref[F, Chunk[Byte]], Ref[F, Long], Ref[F, Long])

It's the only suspect remaining (in my understanding). Does this mean that when the outer stream completes, is causes `onFinalize` on the inner stream that it emits (with a `.map`) as well?

**Comment by nikiforo** [comment]
> 1. eliminate the inner stream compilation: https://github.com/yurique/fs2/tree/feature/js-compression-platform-no-inner-compile ( [code](https://github.com/yurique/fs2/blob/feature/js-compression-platform-no-inner-compile/core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala#L265-L348) )

```scala
def run: IO[Unit] = {
    val bytes: List[Chunk[Byte]] =
      List(
        Chunk(31, -117, 8, 24, 0, 0, 0, 0, 4, 7, 63, 63, 63, 63, 0, 63),
        Chunk(63, 63, 63, 0, 123, 51, 119, -54, -5, -27, -13, 30, -50),
        Chunk(95, -14, 104, -59, 46, 0, 1, 47, 50, -67, 12, 0, 0, 0),
      )

    val c: Compression[IO] = Compression[IO]

    Stream
      .emits(bytes)
      .flatMap(Stream.chunk)
      .debugChunks() // *
      .through(c.gunzip(8192))
      .flatMap(_.content)
      .compile
      .drain
  }
```
This raises error. If you comment out (*), it won't 🤷

**Comment by mpilquist** [comment]
I can take a closer look at the implementation but I strongly suspect the inner stream compilation needs to go even if you can get the tests passing (if the inner stream ends up capturing the tail of the outer stream the way it was yesterday). E.g., what if the stream being inflated has its own resources? Those may be released twice then.

**Comment by yurique** [comment]
> inner stream compilation

Can you clarify which compilation you mean here? I've removed the `.compile` completely, the structure right now is like this:

```
input =>
  Stream.eval ( prepare the `Ref`s).map { case ( ...refs )  => // not flatMap 
  
    val inflatedStream = 
      Stream.bracket(create the inflater)(free the inflater).flatMap { inflater => 
        val pull = ... 
        // pulls the input, feeds it into the inflater, outputs the results from the inflater until it's done
        // then getting the final few bytes (using uncons, not calling compile) and setting the refs in the end
        pull.stream
      }

    return (inflatedStream, ...refs)
  }
```

**Comment by nikiforo** [comment]
> I can take a closer look at the implementation

If you decide to look, [this](https://github.com/nikiforo/fs2/blob/js-compression/core/jvm/src/main/scala/fs2/compression/Issue2785.scala#L119) version prints:
```scala
Chunk(31, -117, 8, 24, 0, 0, 0, 0, 4, 7, 63, 63, 63, 63, 0, 63)
Chunk(63, 63, 63, 0, 123, 51, 119, -54, -5, -27, -13, 30, -50)
Chunk(95, -14, 104, -59, 46, 0, 1, 47, 50, -67, 12, 0, 0, 0)
pull remaining
finalize
end()
Setting refs
```
and fails with the error

**Comment by mpilquist** [comment]
Here's a minimization modeled after the gunzip code, where the `debugChunks` call results in the finalizer getting run before the `case None` in `p1`. Note `p2` is necessary to cause the inversion -- without `p2` things work as expected. So this is likely a case where scope tree ends up messed up somehow and a scope is closed earlier than expected.

```scala
// using scala 3.1.0
// using lib co.fs2::fs2-io:3.2.4

import cats.effect.*
import fs2.*

object Main extends IOApp.Simple:
  def run: IO[Unit] =
    val p1 = (src: Stream[IO, Int]) => Stream.bracket(IO.println("acquired"))(_ => IO.println("finalized")).flatMap { _ =>
      def loop(s: Stream[IO, Int]): Pull[IO, Int, Unit] =
        s.pull.uncons1.flatMap {
          case Some((hd, tl)) => Pull.eval(IO.println(hd)) >> loop(tl)
          case None => Pull.eval(IO.println("reached end"))
        }
      loop(src).stream
    }
    val p2 = (src: Stream[IO, Int]) => 
      src.pull.unconsN(2).flatMap {
        case Some((_, tl)) => p1(tl).pull.echo
        case None => Pull.done
      }.stream

    Stream.range(0, 10)
      .debugChunks()
      .through(p2)
      .compile.drain
```

**Comment by mpilquist** [comment]
Replacing `debugChunks()` with `flatMap(i => Stream(i))` results in correct behavior whereas `flatMap(i => Stream(i)).interruptScope` fails in same was as with `debugChunks()`.

**Comment by mpilquist** [comment]
I confirmed this same behavior as far back as fs2 2.0.0

**Comment by mpilquist** [comment]
Using the following:

```scala
val p1 = (src: Stream[IO, Int]) => Stream.bracket(Ref.of[IO, Boolean](true))(_.set(false)).flatMap { r =>
  def loop(s: Stream[IO, Int]): Pull[IO, Int, Unit] =
    s.pull.uncons1.flatMap {
      case Some((hd, tl)) => Pull.eval(IO.println(hd)) >> loop(tl)
      case None => Pull.eval(r.get.flatMap(b => if (b) IO.unit else IO.raiseError(new Exception("closed early"))))
    }
  loop(src).stream
}

val p2 = (src: Stream[IO, Int]) => 
  src.pull.uncons.flatMap {
    case Some((_, tl)) => p1(tl).pull.echo
    case None => Pull.done
  }.stream
```

The following works:

```scala
scala> val result = Stream(1)
     |     .through(p2)
     |     .compile.drain
     |     .attempt
     |     .unsafeRunSync()
18bb2143 InScope(<function1>,false)
7dce6828 Uncons(Output(Chunk(1)))
7dce6828 Output(Chunk(1))
7dce6828 FlatMapOutput(InScope(<function1>,false),fs2.Stream$$Lambda$7702/0x00000008021377f0@108b8a0)
7dce6828 InScope(<function1>,false)
73281906 Acquire(IO(...),fs2.Stream$$$Lambda$7699/0x0000000802133730@3b4042d7,false)
73281906 Output(Chunk(cats.effect.kernel.Ref$SyncRef@6a44c71b))
73281906 InScope(<function1>,false)
6c48fcb3 Uncons(Succeeded(()))
6c48fcb3 Succeeded(())
6c48fcb3 Eval(IO(...))
6c48fcb3 SucceedScope(cats.effect.kernel.Unique$Token@6c48fcb3)
73281906 Succeeded(())
73281906 SucceedScope(cats.effect.kernel.Unique$Token@73281906)
7dce6828 SucceedScope(cats.effect.kernel.Unique$Token@7dce6828)
18bb2143 Succeeded(())
18bb2143 Succeeded(())
val result: Either[Throwable,Unit] = Right(())
```

And this fails:
```scala
scala> val result = Stream(1)
     |     .map(identity)
     |     .through(p2)
     |     .compile.drain
     |     .attempt
     |     .unsafeRunSync()
7d1b21f8 InScope(<function1>,false)
5d357ed0 Uncons(InScope(<function1>,true))
5d357ed0 InScope(<function1>,true)
c317f19 Uncons(Output(Chunk(1)))
c317f19 Output(Chunk(1))
c317f19 Output(Chunk(1))
c317f19 FlatMapOutput(InScope(<function1>,false),fs2.Stream$$Lambda$7702/0x00000008021377f0@49c17049)
c317f19 InScope(<function1>,false)
b0f0ccf Acquire(IO(...),fs2.Stream$$$Lambda$7699/0x0000000802133730@29b0f713,false)
b0f0ccf Output(Chunk(cats.effect.kernel.Ref$SyncRef@2a931ee2))
b0f0ccf InScope(<function1>,false)
63c242ff Uncons(<function1>)
63c242ff Uncons(Succeeded(()))
63c242ff Succeeded(())
63c242ff SucceedScope(cats.effect.kernel.Unique$Token@c317f19)
5d357ed0 Succeeded(())
5d357ed0 Eval(IO(...))
5d357ed0 FailedScope(cats.effect.kernel.Unique$Token@63c242ff,java.lang.Exception: closed early)
5d357ed0 Fail(java.lang.Exception: closed early)
b0f0ccf FailedScope(cats.effect.kernel.Unique$Token@5d357ed0,java.lang.Exception: closed early)
7d1b21f8 Fail(java.lang.Exception: closed early)
7d1b21f8 Fail(java.lang.Exception: closed early)
val result: Either[Throwable,Unit] = Left(java.lang.Exception: closed early)
```

The key difference is `SucceedScope` which closes off a whole scope subtree (consisting of a child scope that has the allocated resource).

Note this is using a locally modified interpreter that prints each node as its interpreted along with the current scope id.

**Comment by mpilquist** [comment]
Here's a slightly further minimization:

```scala
  test("proper release of bracket in nested pulls") {
    Stream(1)
      .map(identity)
      .pull
      .uncons
      .flatMap {
        case Some((_, tl)) =>
          Stream
            .bracket(Ref.of[IO, Boolean](true))(_.set(false))
            .flatMap { r =>
              tl.pull.uncons.flatMap {
                case Some(_) => throw new Err
                case None =>
                  Pull.eval(r.get.flatMap(b => if (b) IO.unit else IO.raiseError(new Err)))
              }.stream
            }
            .pull
            .echo
        case None => Pull.done
      }
      .stream
      .compile
      .drain
  }
```

This snippet, like all the others in this issue, make the assumption that in a program with structure:

```scala
Stream.bracket(acquire)(finalize).flatMap(r => r.pull.uncons(f).stream)
```

...that `f` always sees the allocated resource `r` as open / non-finalized. This isn't true though - consider `++`, which is implemented as `pull.echo.flatMap(_ => that.pull.echo)`. If the assumption above held in general, then all resources would have their lifetimes extended to the full lifetime of the stream!

One undesirable property of the current implementation is that the observed behavior changes based on what happens after -- i.e., if we comment out the `map(identity)`, then the innermost `case None` is evaluated prior to resource finalization. In the former case, an intermediate scope tree is closed, closing all children. In the latter case, that same scope tree unwinds naturally, from leaf up.

We can support this case by adding a new combinator to `Pull`:

```scala
  def lease: Pull[F, O, R] =
    Pull.bracketCase[F, O, Lease[F], R](
      Pull.getScope[F].evalMap(_.lease),
      _ => this,
      (l, _) => Pull.eval(l.cancel).rethrow
    )
```

This combinator leases all open resources for the lifetime of the target pull. The example then becomes:

```scala
  test("proper release of bracket in nested pulls".only) {
    Stream(1)
      .map(identity)
      .pull
      .uncons
      .flatMap {
        case Some((_, tl)) =>
          Stream
            .bracket(Ref.of[IO, Boolean](true))(_.set(false))
            .flatMap { r =>
              tl.pull.uncons
                .flatMap {
                  case Some(_) => throw new Err
                  case None =>
                    Pull.eval(r.get.flatMap(b => if (b) IO.unit else IO.raiseError(new Err)))
                }
                .lease
                .stream
            }
            .pull
            .echo
        case None => Pull.done
      }
      .stream
      .compile
      .drain
  }
```

**Comment by yurique** [comment]
@mpilquist thanks so much for the analysis and the explanation! 🙇  🙂
