### ISSUE TITLE
Stream.resource/Stream.bracket release action is not being completed when stream is interrupted

### ISSUE THREAD

**Issue by allter** [typelevel/fs2#2966]
When lifting Resource to Stream using Stream.resource, or when using Stream.bracket, then "acquire" action is treated correctly, but "release" action is not.

The expected behaviour is that when interrupting stream execution, the Resource/bracket release actions are executed without interruption before advancing to other stream finalizers.

The actual behavior is that other stream finalizers run immediately after interruption, and if program exits right after this, then the release action is not completed.

Everything works OK if the stream is wrapped into an outer stream using parJoin (and this is a workaround)

fs2: 3.2.12
cats-effect: 3.3.14

Example code ( [scastie](https://scastie.scala-lang.org/8WCJmUBERF2Rzy0aQCUf1w) )
```scala
import cats.effect.{ExitCode, IO, IOApp, Resource, Async, Sync, Temporal}
import cats.effect.syntax.all._
import cats.syntax.all._
import fs2.Stream

import scala.concurrent.duration.DurationInt

object BracketTest extends IOApp {
  case class RunF[F[_]: Async]() {
    def say(msg: String) = Sync[F].delay(println(msg))

    val sleeper = (
      Temporal[F].sleep(1.seconds) *>
        say("slept")
    ).replicateA(4).void

    val sleeperResource = Resource
      .make(sleeper)(_ =>
        say("releasing sleeper resource...") *>
          sleeper *>
          say("released sleeper resource")
      )

    val stream =
      Stream.resource(sleeperResource).evalTap(_ => say("using resource")).void
        .onFinalizeCase(ec =>
          say(s"Finalized with ec=$ec")
        )

    val runF =
      stream.compile.drain // Resource is not released OK
      //Stream(stream).parJoinUnbounded.compile.drain // Resource is released OK
  }

  override def run(args: List[String]): IO[ExitCode] = for {
    _ <- RunF[IO]().runF.timeout(6.seconds)
  } yield ExitCode.Success
}
```

**Comment by armanbilge** [comment]
Here's a further minification.

```scala
//> using scala "3.1.3"
//> using lib "co.fs2::fs2-core::3.2.12"

import cats.effect._
import fs2._

import scala.concurrent.duration._

object BracketTest extends IOApp.Simple {
  def run = Stream
    .bracket(IO.unit)(_ =>
      IO.println("releasing") *>
        IO.sleep(2.seconds) *>
        IO.println("released")
    )
    .compile
    .drain
    .timeout(1.seconds)
}
```

```
$ scala-cli bug.scala
releasing
java.util.concurrent.TimeoutException: 1 second
        at timeout @ BracketTest$.run(bug.scala:18)
        at timeout @ BracketTest$.run(bug.scala:18)
        at timeout @ BracketTest$.run(bug.scala:18)
        at main$ @ BracketTest$.main(bug.scala:9)
        at *> @ BracketTest$.run$$anonfun$1(bug.scala:13)
```

**Comment by diesalbla** [comment]
@allter Could you also try this bug example in previous versions of `fs2`, to see if the behaviour changes? That could allow us to pinpoint the changes that may have caused it.

**Comment by allter** [comment]
> @allter Could you also try this bug example in previous versions of `fs2`, to see if the behaviour changes? That could allow us to pinpoint the changes that may have caused it.

I tested this on different versions of fs2/cats-effect and target IOs. release action did not work anywhere without parJoin. There was numerous cases where acquire action did not work too (e.g. fs2 2.5.11 + latest CE2 IO/monix Task, but not zio 1.0.16), but I think that it's because of wrongly implemented CE typeclasses for that IOs.

I did not try to check with ZIO+CE3 yet since i haven't them in my prod. Also i did not test fs2 3.x.x much.

**Comment by mpilquist** [comment]
In @armanbilge's original reproduction, note that the stream is already being finalized, and the timeout is then being applied to waiting for finalization.

```scala
//> using scala "3.1.3"
//> using lib "co.fs2::fs2-core::3.2.12"

import cats.effect._
import fs2._

import scala.concurrent.duration._

object BracketTest extends IOApp.Simple {
  def run = Stream
    .bracket(IO.unit)(_ =>
      IO.println("releasing") *>
        IO.sleep(2.seconds) *>
        IO.println("released")
    )
    .compile
    .drain
    .timeout(1.seconds)
}
```

If we instead cancel the program while the stream is still running, we get the expected back pressure:

```scala
//> using scala "3.1.3"
//> using lib "co.fs2::fs2-core::3.2.12"

import cats.effect._
import fs2._

import scala.concurrent.duration._

object BracketTest extends IOApp.Simple {
  def run = Stream
    .bracket(IO.unit)(_ =>
      IO.println("releasing") *>
        IO.sleep(2.seconds) *>
        IO.println("released")
    )
    .flatMap(_ => Stream.never[IO])
    .compile
    .drain
    .timeout(1.seconds)
}
```

**Comment by mpilquist** [comment]
@armanbilge This example appears to have the correct behavior:
```scala
//> using scala "3.1.3"
//> using lib "co.fs2::fs2-core::3.2.12"

import cats.effect._
import fs2._

import scala.concurrent.duration._

object BracketTest extends IOApp.Simple {
  def run = Stream
    .bracket(IO.unit)(_ =>
      IO.canceled *> IO.println("released")
    )
    .compile
    .drain
}
```

**Comment by armanbilge** [comment]
Are you sure? I don't see the "released" `println`. Compare with:
```scala
//> using scala "3.1.3"
//> using lib "co.fs2::fs2-core::3.2.12"

import cats.effect._
import fs2._

import scala.concurrent.duration._

object BracketTest extends IOApp.Simple {
  def run = Resource.make(IO.unit)(_ => IO.canceled *> IO.println("released")).use_
}
```

**Comment by mpilquist** [comment]
Run just this and see that there's nothing printed:

```scala
def run = IO.canceled *> IO.println("released")
```

**Comment by armanbilge** [comment]
Sure, but that's not part of a resource release. Is `Stream.bracket` not supposed to behave like `Resource.make`? What about lifting a `Resource` into a stream? AFAIU release should be uncancelable.
