### ISSUE TITLE
The instances allocated in the `Stream#flatmap` are referenced in the `Pull#BindBind` which can't be GCed before the whole Stream ends

### ISSUE THREAD

**Issue by floating-cat** [typelevel/fs2#2969]
fs2 version: 3.0.3 and 3.2.12
Full reproduction code: https://github.com/floating-cat/fs2-netty/tree/memory_leak
Related code line: https://github.com/floating-cat/fs2-netty/blob/memory_leak/core/src/main/scala/fs2/netty/SocketHandler.scala#L59-L64

Steps:
1. Clone the whole project above.
2. Run `src/main/scala/fs2/netty/benchmarks/echo/Fs2Netty.scala` with host and port arguments for listening.
3. Run `benchmarks/rps.sh` to benchmark it. (this script needs [rust_echo_bench](https://github.com/haraldh/rust_echo_bench) command, and you may need to use the `cargo run --release -- --help` command to compile it)

Result:
The program causes a memory leak and If I use `-Xmx200m -XX:MaxDirectMemorySize=200m`, the program can out of memory.

The related code is like the below:

```scala
lazy val reads: Stream[F, Byte] =
    Stream.force {
      Functor[F].ifF(isOpen)(
        // note the `++ reads` code here
        // I found a lots of `toChunk(b)` instances referenced in the `Pull#BindBind` which can't be GC
        // before this whole Stream ends and leaks memory a lot.
        fetch.flatMap(b => if (b == null) Stream.empty else Stream.chunk(toChunk(b)) ++ reads)
        Stream.empty
      )
    }

val fetch: Stream[F, ByteBuf] = ???
// wraps the `buf` in the `Chunk.ByteBuffer`
def toChunk(buf: ByteBuf): Chunk[Byte] = ???
```

When the Stream is very long and I found all `toChunk(b)` instance is referenced in the `Pull#BindBind` which can't be GC before this whole Stream ends and leaks memory a lot.

![image](https://user-images.githubusercontent.com/6748077/187018982-79744b83-fd4c-4882-9363-8121df911281.png)
[memory snapshot here](https://github.com/typelevel/fs2/files/9437477/Fs2Netty_39958_27.08.2022_15.27.38.hprof.zip)

If I use the below code instead it doesn't have this issue.
It seems the fs2's Steam#flatmap can all capture all instances in it so causing this issue.

One way with different semantics:
// moved the `reads` outside `flatmap`
`fetch.flatMap(b => if (b == null) Stream.empty else Stream.chunk(toChunk(b))) ++ reads`.

Second way:
```scala
lazy val reads: Stream[F, Byte] =
    Stream.force(Functor[F].ifF(isOpen)(
      fetchOpt.map(buffOpt => buffOpt.map(toChunk)),
      Stream(None)
    ))
      .repeat.unNoneTerminate.unchunks
val fetchOpt: Stream[F, Option[ByteBuf]] = ??? 
 ```
 
Is this behavior intended or might a memory leak issue? Thanks.

**Comment by mpilquist** [comment]
The issue appears to be caused by `reads` being defined as a `lazy val`. Changing it to a `def` avoids the leak. Here's a small reproduction (which can be placed at the bottom of `MemoryLeakSpec.scala` and run from SBT via `coreJVM/IntegrationTest/test`).

**Comment by mpilquist** [comment]
Next step is getting a test case added to `MemoryLeakSpec.scala` that reliably reproduces the issue. If anyone is successful in doing so, please post here, thanks!

**Comment by floating-cat** [comment]
@mpilquist Hi, I have found a simple test case based your example below:

```
  leakTest("2969".only) {
    def largeChunk = Chunk.array(new Array[Int](1000000))
    val fetch: Stream[IO, Chunk[Int]] =
      Stream.bracketFull[IO, Chunk[Int]](_ => IO.delay(largeChunk)) { (_, _) =>
        IO.unit
      }
      // not have this problem
      // Stream.eval(IO(largeChunk))

    lazy val reads: Stream[IO, Int] =
      Stream.force {
        cats
          .Functor[IO]
          .ifF(IO(true))(
            fetch.flatMap(c => Stream.chunk(c) ++ reads),
            Stream.empty
          )
      }

    reads
  }
```

This issue is not related to `lazy val` vs `def`. I tried to use the `def` in my original code and have this issue too.
But it seems related to `Stream.bracketFull`.
If I use the `Stream.eval(IO(largeChunk))` instead, I don't have this problem.

**Comment by floating-cat** [comment]
also cc @diesalbla. I saw that you need a test in #2970. I have one in the above comment.

**Comment by floating-cat** [comment]
I have rechecked my test code and original code. This is my mistake. I forget that I use the `Stream.bracketFull` and its `flatmap` here so it still holds the reference and causes the memory leak.
So I am closing this issue.
