### ISSUE TITLE
StackOverflowError on flatMap of Pure stream to an empty stream

### ISSUE THREAD

**Issue by TomasMikula** [typelevel/fs2#3011]
fs2 version 3.3.0

Reproduction case:

```scala
fs2.Stream
  .emits(List.fill(100000)(()))
  .flatMap(_ => fs2.Stream.empty)
  .compile
  .drain
```

**Comment by mpilquist** [comment]
This worked in 3.0.0 but has failed since 3.1.0 at least. I haven't tried the versions between 3.0.0 and 3.1.0 yet though (and will likely be unable to today).
