### ISSUE TITLE
Scope lookup failure with `hold1`

### ISSUE THREAD

**Issue by Jasper-M** [typelevel/fs2#3081]
If I use `hold1` my stream terminates with an error:

> java.lang.RuntimeException: Scope lookup failure!
> 
> This is typically caused by uncons-ing from two or more streams in the same Pull.
> To do this safely, use `s.pull.stepLeg` instead of `s.pull.uncons` or a variant
> thereof. See the implementation of `Stream#zipWith_` for an example.

If I switch to `holdOption` the problem goes away.

```scala
val s2 = for {
  sig <- Stream.range(0, 10).covary[IO].metered(50.millis).debug(x => s"SIG: $x").hold1
  res <- Stream.range(0, 10).covary[IO].metered(120.millis).debug(x => s"STREAM: $x").evalMap(x => sig.get.map(x -> _))
} yield res

s2.printlns.onFinalize(IO.println("END")).compile.drain.unsafeRunSync()
```
output:
```
SIG: 0
END
java.lang.RuntimeException: Scope lookup failure!
...
```

Scastie: https://scastie.scala-lang.org/dLpc9VlJRs6DbWu2uUQMGg

**Comment by armanbilge** [comment]
@Jasper-M since you are becoming a regular contributor: would you be interested to work on this? 😁 I guess the solution is to just do what the exception says and replace the `uncons` with `stepLeg`.

**Comment by Jasper-M** [comment]
If I understood why it doesn't work in the first place 😅

**Comment by armanbilge** [comment]
> Actually I think this is a fundamental issue with `uncons`: it seems unsafe to use it to build stream combinators if you do not control the `Stream` you are unconsing.

Ok, this statement was probably a bit overblown 😅 sorry. After playing with it some more, `uncons` is not the issue, since I have the same problem after rewriting with `stepLeg`. The problem seems to be running the tail of a `zip`ped `Stream `.concurrently`.
