### ISSUE TITLE
Subscribing to a closed Topic <-> Stream.never

### ISSUE THREAD

**Issue by Jasper-M** [typelevel/fs2#3083]
The following program times out after 5 seconds. 

Of course the idea is that in a real program the publishing stream and the subscriptions are running in separate fibers so that `topic.close` and `topic.subscribe` are effectively racing each other.

I think it would be safer if subscribing to a closed `Topic` results in `Stream.empty` instead of `Stream.never`.

```scala
val program = for {
  topic <- Topic[IO, Int]
  _ <- Stream(1, 2, 3).through(topic.publish).compile.drain
  _ <- topic.subscribeUnbounded.compile.drain
} yield ()

program.timeout(5.seconds).unsafeRunSync()
```

https://scastie.scala-lang.org/UXRTQicrRKuCqkxTJP1Dlw

**Comment by armanbilge** [comment]
I agree, the proposed semantic makes more sense. I wonder what the semantics are for `Channel#stream` when the `Channel` is closed? Seems like they should align.

**Comment by Jasper-M** [comment]
This returns immediately:
```scala
Channel.unbounded[IO, Int].flatMap{ch => ch.close *> ch.stream.compile.drain }.unsafeRunSync()
```

**Comment by armanbilge** [comment]
Thanks for checking. That seems reason enough for me, would you like to open a PR? :)

**Comment by Jasper-M** [comment]
I can take a stab at it.
