### ISSUE TITLE
`StreamDecoder.many` fails silently on nested length-delimited codecs

### ISSUE THREAD

**Issue by lucianojoublanc-da** [typelevel/fs2#3104]
`StreamDecoder.many` repeatedly accrues bits from a stream and attempts to decode them. If it fails to decode, it just waits for more bits to arrive and tries again (I think).

The implementation seems to rely on seeing the `InsufficentBits` error condition, here:

https://github.com/typelevel/fs2/blob/d4307552fe63d9eaed76588b92090cb077bef713/scodec/shared/src/main/scala/fs2/interop/scodec/StreamDecoder.scala#L96

The problem with this is that if you have nested length-delmited codec, for instance:

```scala
variableSizeBytesLong(unit32, variableSizeBytesLong(uint32, ...))
```

and if it fails on the _inner_ codec, the entire stream fails silently. I think in this case, it continues accruing bits forever.

**Comment by diesalbla** [comment]
@ChristopherDavenport @lucianojoublanc-da Do you have a minimised reproducer? A Scala-CLI script would be helpful.

**Comment by ChristopherDavenport** [comment]
I must regret/pleased(depending on the audience) to inform that on further minimization it was my own fault, and not that of the stream decoder.

**Comment by lucianojoublanc-da** [comment]
Sorry was on leave ...

> @ChristopherDavenport @lucianojoublanc-da Do you have a small reproducer? A Scala-CLI script would be helpful.

This isn't exactly as I reported it, but I hope it's correct: https://gist.github.com/lucianojoublanc-da/153c6047f81d53ed9004cc3f428530d2

Essentially you have an infinite stream printing out length-delimited values, except they're missing the payload (the `int32`). This should throw an `InsufficientBits` exception, but the above-linked `many` just loops on seeing this error. It should fail, reporting a decode error.

The original example I gave was of a 'nested' `variableLengthBytes`, which when run _does_ terminate, but without any return value (instead of a decode failure).

**Comment by nikiforo** [comment]
> `StreamDecoder.many` repeatedly accrues bits from a stream and attempts to decode them. If it fails to decode, it just waits for more bits to arrive and tries again (I think).

You're correct. If there is an `InsufficientBits` error `StreamDecoder` SHOULD wait for more bits. That's the expected behavior.

> The problem with this is that if you have nested length-delmited codec, for instance:

Could you please provide some other reproduction, because from my POV the one you've provided works as expected. If you move `.debug()` to the line before `.compile` you'll see a console of infinite `8` that were decoded. In your example you're waiting for the last value of an infinite stream.

**Comment by mpilquist** [comment]
Please reopen if still a problem, thanks!
