### ISSUE TITLE
groupWithin: inconsistent behaviour on source termination

### ISSUE THREAD

**Issue by Angel-O** [typelevel/fs2#3169]
### [scastie](https://scastie.scala-lang.org/HAeMqP3BTXSUBGuf2eqPMg)

While playing around with a new implementation of groupWithin I discovered a bug. The combinator doesn't handle upstream termination consistently. See below

```scala
    val finiteStream = Stream
      .range(0, 4)
      .covary[IO]
      .metered(1.second)

    val doesNotTerminate = 
        finiteStream
          .groupWithin(Int.MaxValue, 2.days) 
          .evalTap(IO.println)
          .compile
          .lastOrError.void

    val terminates =
         finiteStream
          .groupWithin(8, 2.days)
          .evalTap(IO.println)
          .compile
          .lastOrError.void
```

I have an idea why this is happening. I'm happy to take a look 💪🏾 

The question I have though is: what's the correct behaviour here ?
 - terminating the stream when upstream terminates 
 - keeping the stream alive

**Comment by armanbilge** [comment]
I believe that when the upstream terminates, the entire stream should terminate (gracefully, i.e. no lost elements).
