### ISSUE TITLE
Unintended unchunking when using Monad instance of Stream

### ISSUE THREAD

**Issue by bwiercinski** [typelevel/fs2#3187]
When using implementations of cats' type classes instances `fs2.Stream#monadErrorInstance` or `fs2.StreamLowPriority#monadInstance` unchunking will occur as a side effect.

```scala
def testCase(pipe: Pipe[fs2.Pure, Int, (Int, Int)]) = (Stream(1,2,3) ++ Stream(4,5,6)) .through(pipe).chunks.toList

testCase(_.map(e => e -> (e + 1)))
// List(Chunk((1,2), (2,3), (3,4)), Chunk((4,5), (5,6), (6,7)))

testCase(_.fproduct(_ + 1))
// List(Chunk((1,2)), Chunk((2,3)), Chunk((3,4)), Chunk((4,5)), Chunk((5,6)), Chunk((6,7)))
```

This happens because the default implementation of `map` in `Monad` is `flatMap(fa)(a => pure(f(a)))`. I believe that overriding that default implementation in mentioned instances using:
```scala
override def map[A, B](fa: Stream[F, A])(f: A => B): Stream[F, B] = fa.map(f)
```
will fix that. I think such unchunking may decrease the performance. By a lot?

**Comment by armanbilge** [comment]
Good catch, if we are missing that override we should definitely add it :)

**Comment by yyy1000** [comment]
I'm interested in it. :)

**Comment by diesalbla** [comment]
@bwiercinski That's right. Go ahead and PR :) 👍🏼 

We already have performance-motivated overrides of methods with a default implementation in `cats`, such as Chunk `traverse_` for singleton or empty chunks.
