### ISSUE TITLE
rechunkRandomly sometimes emits everything in a single chunk

### ISSUE THREAD

**Issue by Jasper-M** [typelevel/fs2#3195]
I have five 1-element chunks and a maxFactor of 2.0, but with certain seeds `rechunkRandomly` emits all elements in a single chunk. The number of chunks in the input stream doesn't matter. If you have 10000 1-element chunks, you end up with a single 10000-element chunk.

```scala
val fiveChunks = Stream(1) ++ Stream(2) ++ Stream(3) ++ Stream(4) ++ Stream(5)

fiveChunks.rechunkRandomlyWithSeed(0.1, 2.0)(5).chunks.toList == List(Chunk(1,2,3,4,5))
```
https://scastie.scala-lang.org/TqE3oVzwQ2asDEdW8rf3uA

Other example of a wrong result:
```scala
scala> (Stream(1,1) ++ Stream(2,2) ++ Stream(3,3) ++ Stream(4,4) ++ Stream(5,5)).rechunkRandomlyWithSeed(0.1, 2.0)(9).chunks.toList
val res16: List[fs2.Chunk[Int]] = List(Chunk(1), Chunk(1, 2, 2, 3, 3, 4, 4, 5, 5))
```

**Comment by diesalbla** [comment]
@Jasper-M Can you check if this bug happened a few versions back ? We recently changed this method in https://github.com/typelevel/fs2/pull/3095

**Comment by Jasper-M** [comment]
The bug also seems to be present in 3.4.0.
The issue seems to occur if you get nextSize == 0 a number of times in a row.

**Comment by yyy1000** [comment]
Hi, I want to help with this.
