### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by danthemangold** [typelevel/fs2#3200]
https://github.com/typelevel/fs2/blob/aa60723a86199210eb5f557c6892be4471040775/reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala#L87

"is" should be "if"

**Comment by diesalbla** [comment]
@danthemangold Feel free to open PR.

**Comment by nikita12100** [comment]
Sorry if something wrong, it's my first time contributing.
https://github.com/typelevel/fs2/pull/3216
