### ISSUE TITLE
Add `Channel#sendClose`

### ISSUE THREAD

**Issue by armanbilge** [typelevel/fs2#3279]
And also maybe `Channel#trySendClose`. Naming subject to bikeshed e.g. `sendAndClose`? 

The idea is to be able to atomically `send` a final element to the `Channel` and immediately `close` it. With `ch.send(...) *> ch.close` there is a possibility that another concurrent `send` can sneak between.

Motivation: in https://github.com/http4s/http4s/pull/7196 we want to `close` the `Channel` immediately upon sending a WebSocket CloseFrame.

@tothpeti has kindly volunteered to work on this :)

**Comment by tothpeti** [comment]
I would like to work on this one :)
