### ISSUE TITLE
sbt doc task fails for scala 3 and fs2-io

### ISSUE THREAD

**Issue by eikek** [typelevel/fs2#3293]
Hello,

When upgrading to fs2 3.9.1 I noticed that the sbt `doc` command fails in my library, but only for Scala 3 and when it depends on fs2-io. It seems to me that the `@nowarn213` annotation cannot be resolved.

```
[error] -- Error: io/shared/src/main/scala/fs2/io/io.scala:35:0 ------------------------
[error] undefined: new org.typelevel.scalaccompat.annotation.package.nowarn213 # -1: TermRef(TypeRef(TermRe
f(TermRef(ThisType(TypeRef(NoPrefix,module class scalaccompat)),object annotation),package),nowarn213),<ini
t>) at readTasty
[info] Main Scala API documentation to /home/eike/workspace/projects/emil/modules/markdown/target/scala-3.3
.0/api...
[error] one error found
```

When I add the dependency:
```
"org.typelevel" %% "scalac-compat-annotation" % "0.1.2"
```

it works fine. Is this dependency required to add now? it is all good for Scala 2.12 and 2.13, though.

Thanks and kind regards!

**Comment by armanbilge** [comment]
Sorry for the trouble.

> Is this dependency required to add now?

It's not supposed to be required, but that seems to be the workaround 😕 

I opened this issue in Scala 3 repository:
- https://github.com/lampepfl/dotty/issues/18487

**Comment by eikek** [comment]
> Sorry for the trouble.

No worries at all! Thank you very much for such a quick response!
