### ISSUE TITLE
Root `Path` is incorrectly handled in ScalaJS

### ISSUE THREAD

**Issue by InversionSpaces** [typelevel/fs2#3353]
fs2 version: `3.9.3`

Reproduction example:
```scala
import fs2.io.file.Path

val p = Path("/")
println(p.normalize.absolute)
```
Outputs current working directory instead of `/` when run in JS.

Happens because of this code:
https://github.com/typelevel/fs2/blob/53f458d6ac4044df2b8e2d4310b92a1fb8953d80/io/js/src/main/scala/fs2/io/file/Path.scala#L102-L105

**Comment by armanbilge** [comment]
Thanks for reporting! Since you've already identified the broken code, would you be interested to fix it as well? 😄

**Comment by InversionSpaces** [comment]
I am willing to provide a PR, but I am not quite sure how to fix that. I would just store user provided string inside `Path`, but the commit that added this `sep` drop is named `bug fixing`, so I guess it is needed for some reason to drop that sep?
https://github.com/typelevel/fs2/commit/d18ddd53d04f8ce5bd58df555d17180c2daded91#diff-9fdf8bd4af13b084b80dc62144301802026204db7caabef1b0bcd64ab84daefdL74

**Comment by armanbilge** [comment]
> I am not quite sure how to fix that.

It's possible that we may need to special-case this scenario.

> so I guess it is needed for some reason to drop that sep

Can't remember at this point 😅 😬 you can try undoing that and see if any tests fail, and why.

**Comment by armanbilge** [comment]
Aha, probably to match JVM behavior.

```
$ scala
Welcome to Scala 3.3.0 (17.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> java.nio.file.Paths.get("/foo/")
val res0: java.nio.file.Path = /foo
```
