### ISSUE TITLE
Deprecated Files.walk(start: Path, maxDepth: Int, followLinks: Boolean) ignores maxDepth and followLinks

### ISSUE THREAD

**Issue by sven42** [typelevel/fs2#3412]
Thanks a lot for your fix of #3329 

However, I found that the current implementation in v3.10.0 of the now deprecated Files.walk() ignores some of its parameters.

```
  def walk(start: Path, maxDepth: Int, followLinks: Boolean): Stream[F, Path] =
    walk(start, WalkOptions.Default)
```

should be implemented like this:
```
    walk(start, WalkOptions.Default.withMaxDepth(maxDepth).withFollowLinks(followLinks))
```

**Comment by mpilquist** [comment]
Ouch, thanks for reporting. Want to open a PR?
