### ISSUE TITLE
Stream#mergeHaltL blocks pulling new elements

### ISSUE THREAD

**Issue by CEikermann** [typelevel/fs2#3463]
In this given example, it looks like the combined mergeHaltL and parJoinUnbounded is resulting into block of pulling new input elements:
- https://scastie.scala-lang.org/zJNRVkeGTOG5WgxsUYEOeQ
- Input for "never" and "sub3" never pulled

When using Stream(...).parJoinUnbounded as root stream, everything works as intended
-  https://scastie.scala-lang.org/czOIGW6rQLuErxu78wqi5Q
- Small downside of this approach: The inner stream will run at least the timeout duration, even if the root stream (in) is already terminated

Is this the intended behavior of mergeHaltL, that its blocking pulling new elements in this specific scenario? Effectively I want a timeout stream that runs independently from the input stream, but emits one element downstream

**Comment by mpilquist** [comment]
Thanks for reporting. Minimized a bit to this:

```scala
import cats.effect.IO
import cats.effect.unsafe.implicits.global
import fs2.Stream

val s = Stream(1, 2, 3).chunkLimit(1).unchunks.covary[IO]
s.merge(s)
  .debug(x => s"in: $x")
  .map(i => Stream.eval(IO.println("out> " + i)) ++ Stream.never[IO]) // <--- Fails
  //.map(i => Stream.eval(IO.println("out> " + i))) // <--- Works
  .parJoinUnbounded
  .compile.drain
  .unsafeRunSync()
```

Looks like a strange interaction between `merge` and `parJoinUnbounded` when each output pulled from the merged stream yields a stream that doesn't end.

**Comment by mpilquist** [comment]
The implementation of `merge` races the two input streams and calls [`sendChunk`](https://github.com/typelevel/fs2/blob/e2925a2df97b4b5c2f75aeda394ccd65f4b9f8cc/core/shared/src/main/scala/fs2/Stream.scala#L2049) on each input chunk. Back-pressure is implemented with a semaphore that's released via `onFinalize`.

In a stream with structure `s.map(f).parJoinUnbounded`, we have to make sure any resources open at the time an element is emitted from `s` are open for the duration of the stream returned by `f`.

Unfortunately in the case of `s1.merge(s2).map(_ => Stream.never).parJoinUnbounded`, this means the back-pressure finalization "resource" of each element emitted from `merge` is kept open forever, ensuring only 1 element can be pulled from each side of the merged stream.

**Comment by mpilquist** [comment]
The simplest fix is inserting a `prefetch` before `parJoinUnbounded`: https://scastie.scala-lang.org/i50HEg3TQAmrBoMctjl41A

**Comment by CEikermann** [comment]
@mpilquist thank you for the great insight, so it looks like everything is working as intended, will close this issue
